"""
2026 Compliance Layer — AI Disclosure (FINAL)
Automatically appended to ALL AI-generated outputs.
Cannot be removed by end users.

Utah AI Policy Act (SB 149) + Colorado AI Act (SB 205) + EU AI Act Article 50

INTEGRATION: This module is called from ai_engine.py at the end of every
process_document() call. The disclosure is embedded in the output JSON.
"""
from datetime import datetime

# ═══ DISCLOSURE TEXTS (cannot be modified by end users) ═══

DISCLOSURE_LABEL = "Generated by DocuAction AI \u2013 AI-generated content. Review recommended before use."

DISCLOSURE_FOOTER_PDF = """
────────────────────────────────────────────────────────
ARTIFICIAL INTELLIGENCE DISCLOSURE
This document was generated by DocuAction AI, an AI-powered document
intelligence platform developed by Alliance Global Tech, Inc.

In accordance with applicable AI transparency laws:
\u2022 Utah Artificial Intelligence Policy Act (SB 149)
\u2022 Colorado Artificial Intelligence Act (SB 205)  
\u2022 EU AI Act Article 50

This content was produced by an artificial intelligence system and should
be reviewed by a qualified human before use in any official capacity.

Platform: DocuAction AI v3.2.0
Provider: Alliance Global Tech, Inc.
Model: {model}
Confidence: {confidence}%
Generated: {timestamp}
────────────────────────────────────────────────────────
"""

DISCLOSURE_EMAIL_FOOTER = (
    "\n\n---\n"
    "Generated by DocuAction AI \u2013 AI-generated content. "
    "Review recommended before use.\n"
    "This email was drafted by an AI system and should be reviewed before sending."
)


def attach_disclosure(output: dict, model_used: str = "unknown", confidence: float = 0) -> dict:
    """
    Attach mandatory AI disclosure to any output dict.
    Called automatically by ai_engine.py on every response.
    This disclosure CANNOT be removed by end users.
    """
    output["_disclosure"] = {
        "label": DISCLOSURE_LABEL,
        "ai_generated": True,
        "model_used": model_used,
        "confidence_percent": round(confidence * 100, 1),
        "human_review_required": True,
        "generated_at": datetime.utcnow().isoformat() + "Z",
        "platform": "DocuAction AI v3.2.0",
        "provider": "Alliance Global Tech, Inc.",
        "compliance_references": [
            "Utah Artificial Intelligence Policy Act (SB 149)",
            "Colorado Artificial Intelligence Act (SB 205)",
            "EU AI Act Article 50",
        ],
        "removable": False,
    }

    # If output contains an email body, append email disclosure
    if "body" in output and isinstance(output["body"], str):
        output["body"] = output["body"] + DISCLOSURE_EMAIL_FOOTER

    return output


def get_pdf_footer(model_used: str = "Claude", confidence: float = 0.95) -> str:
    """
    Returns formatted disclosure footer for PDF exports.
    Must be appended to every generated PDF document.
    """
    return DISCLOSURE_FOOTER_PDF.format(
        model=model_used,
        confidence=round(confidence * 100, 1),
        timestamp=datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC"),
    )
