import os  
f=open('app/bulletin_intelligence/engine.py','r')  
c=f.read()  
f.close()  
f=open('app/bulletin_intelligence/engine.py.backup','w')  
f.write(c)  
f.close()  
c=c.replace('from dataclasses import dataclass, asdict, field','from dataclasses import dataclass, asdict, field\nfrom . import boolean_filter as bf')  
c=c.replace('# tasks.append(ingest_gdelt(agency, lookback_hours))','tasks.append(ingest_gdelt(agency, lookback_hours))')  
c=c.replace('tasks.append(ingest_news(agency, lookback_hours))','# tasks.append(ingest_news(agency, lookback_hours))')  
f=open('app/bulletin_intelligence/engine.py','w')  
f.write(c)  
f.close()  
print('DONE')  
