"""
Export Service — Formats structured JSON into readable PDF/DOCX/TXT
Never shows raw JSON to user.
"""
import io
import json
import logging
from datetime import datetime
from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select

from app.core.database import get_db
from app.core.security import get_current_user

logger = logging.getLogger("docuaction.export")
router = APIRouter(tags=["Export"])

DISCLOSURE = "Generated by DocuAction Intelligence Pipeline. This content was produced by an automated analysis system. Human review is recommended before use in decision-making."


def _parse_content(raw):
    """Parse content from DB — could be JSON string or dict."""
    if isinstance(raw, dict):
        return raw
    if isinstance(raw, str):
        try:
            return json.loads(raw)
        except (json.JSONDecodeError, TypeError):
            return {"text": raw}
    return {"text": str(raw)}


def _format_text(data, action_type, model="", confidence=0):
    """Convert structured JSON into clean readable text."""
    lines = []
    lines.append("=" * 60)
    lines.append(f"DocuAction Intelligence Output — {action_type.upper()}")
    lines.append(f"Generated: {datetime.utcnow().strftime('%B %d, %Y %H:%M UTC')}")
    if model:
        lines.append(f"Model: {model} | Confidence: {int(confidence * 100)}%")
    lines.append("=" * 60)
    lines.append("")

    if action_type == "summary":
        if data.get("summary"):
            lines.append("EXECUTIVE SUMMARY")
            lines.append("-" * 40)
            lines.append(data["summary"])
            lines.append("")

        if data.get("key_metrics"):
            lines.append("KEY METRICS")
            lines.append("-" * 40)
            for m in data["key_metrics"]:
                metric = m.get("metric", "")
                value = m.get("value", "")
                context = m.get("context", "")
                lines.append(f"  {metric}: {value}")
                if context:
                    lines.append(f"    {context}")
            lines.append("")

        if data.get("recommendations"):
            lines.append("RECOMMENDATIONS")
            lines.append("-" * 40)
            for i, r in enumerate(data["recommendations"], 1):
                lines.append(f"  {i}. {r}")
            lines.append("")

    elif action_type == "actions":
        if data.get("tasks"):
            lines.append(f"ACTION ITEMS ({len(data['tasks'])})")
            lines.append("-" * 40)
            for t in data["tasks"]:
                priority = (t.get("priority", "medium")).upper()
                lines.append(f"  [{priority}] {t.get('task', '')}")
                lines.append(f"    Owner: {t.get('owner', 'TBD')}  |  Deadline: {t.get('deadline', 'TBD')}")
                lines.append("")

        if data.get("decisions"):
            lines.append(f"DECISIONS ({len(data['decisions'])})")
            lines.append("-" * 40)
            for d in data["decisions"]:
                lines.append(f"  Decision: {d.get('decision', '')}")
                lines.append(f"  Decided by: {d.get('decided_by', 'N/A')}")
                if d.get("impact"):
                    lines.append(f"  Impact: {d['impact']}")
                lines.append("")

        if data.get("follow_ups"):
            lines.append(f"FOLLOW-UPS ({len(data['follow_ups'])})")
            lines.append("-" * 40)
            for f in data["follow_ups"]:
                lines.append(f"  {f.get('item', '')}  |  Owner: {f.get('owner', 'TBD')}  |  Due: {f.get('due', 'TBD')}")
            lines.append("")

    elif action_type == "insights":
        if data.get("insights"):
            lines.append(f"KEY INSIGHTS ({len(data['insights'])})")
            lines.append("-" * 40)
            for ins in data["insights"]:
                impact = (ins.get("impact", "medium")).upper()
                lines.append(f"  [{impact}] {ins.get('finding', '')}")
                if ins.get("evidence"):
                    lines.append(f"    Evidence: {ins['evidence']}")
                if ins.get("recommendation"):
                    lines.append(f"    Recommendation: {ins['recommendation']}")
                if ins.get("confidence"):
                    lines.append(f"    Confidence: {int(ins['confidence'] * 100)}%")
                lines.append("")

        if data.get("risk_factors"):
            lines.append("RISK FACTORS")
            lines.append("-" * 40)
            for r in data["risk_factors"]:
                if isinstance(r, str):
                    lines.append(f"  - {r}")
                elif isinstance(r, dict):
                    lines.append(f"  - {r.get('risk', str(r))}")
            lines.append("")

        if data.get("opportunities"):
            lines.append("OPPORTUNITIES")
            lines.append("-" * 40)
            for o in data["opportunities"]:
                if isinstance(o, str):
                    lines.append(f"  - {o}")
                elif isinstance(o, dict):
                    lines.append(f"  - {o.get('opportunity', str(o))}")
            lines.append("")

    elif action_type == "email":
        if data.get("to"):
            lines.append(f"To: {data['to']}")
        if data.get("subject"):
            lines.append(f"Subject: {data['subject']}")
        lines.append("-" * 40)
        if data.get("body"):
            lines.append(data["body"])
        lines.append("")
        if data.get("attachments_suggested"):
            lines.append("Suggested Attachments:")
            for a in data["attachments_suggested"]:
                lines.append(f"  - {a}")
        lines.append("")

    elif action_type == "brief":
        if data.get("title"):
            lines.append(data["title"].upper())
            lines.append("=" * len(data["title"]))
            lines.append("")

        if data.get("situation"):
            lines.append("SITUATION ANALYSIS")
            lines.append("-" * 40)
            lines.append(data["situation"])
            lines.append("")

        if data.get("key_findings"):
            lines.append(f"KEY FINDINGS ({len(data['key_findings'])})")
            lines.append("-" * 40)
            for f in data["key_findings"]:
                lines.append(f"  Finding: {f.get('finding', '')}")
                if f.get("data"):
                    lines.append(f"  Data: {f['data']}")
                if f.get("source"):
                    lines.append(f"  Source: {f['source']}")
                lines.append("")

        if data.get("metrics_table"):
            lines.append("METRICS")
            lines.append("-" * 40)
            for m in data["metrics_table"]:
                lines.append(f"  {m.get('metric', '')}: Current={m.get('current', '')} | Target={m.get('target', '')} | Status={m.get('status', '')}")
            lines.append("")

        if data.get("risk_assessment"):
            lines.append("RISK ASSESSMENT")
            lines.append("-" * 40)
            for r in data["risk_assessment"]:
                sev = (r.get("severity", "medium")).upper()
                lines.append(f"  [{sev}] {r.get('risk', '')}")
                if r.get("mitigation"):
                    lines.append(f"    Mitigation: {r['mitigation']}")
                lines.append("")

        if data.get("recommendation"):
            lines.append("RECOMMENDATION")
            lines.append("-" * 40)
            lines.append(data["recommendation"])
            lines.append("")

        if data.get("decision_required"):
            lines.append("DECISION REQUIRED")
            lines.append("-" * 40)
            lines.append(data["decision_required"])
            lines.append("")

    else:
        # Fallback: format any dict nicely
        for key, value in data.items():
            if key.startswith("_"):
                continue
            if isinstance(value, str):
                lines.append(f"{key.replace('_', ' ').title()}")
                lines.append("-" * 40)
                lines.append(value)
                lines.append("")
            elif isinstance(value, list):
                lines.append(f"{key.replace('_', ' ').title()} ({len(value)} items)")
                lines.append("-" * 40)
                for item in value:
                    if isinstance(item, dict):
                        for k, v in item.items():
                            if not k.startswith("_"):
                                lines.append(f"  {k}: {v}")
                        lines.append("")
                    else:
                        lines.append(f"  - {item}")
                lines.append("")

    # Disclosure footer
    lines.append("=" * 60)
    lines.append(DISCLOSURE)
    lines.append("=" * 60)

    return "\n".join(lines)


def _build_pdf(text, action_type, model="", confidence=0):
    """Generate PDF from formatted text using ReportLab."""
    try:
        from reportlab.lib.pagesizes import letter
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
        from reportlab.lib.units import inch
        from reportlab.lib.enums import TA_LEFT

        buf = io.BytesIO()
        doc = SimpleDocTemplate(buf, pagesize=letter, topMargin=0.75 * inch, bottomMargin=0.75 * inch, leftMargin=0.75 * inch, rightMargin=0.75 * inch)
        styles = getSampleStyleSheet()

        title_style = ParagraphStyle("CustomTitle", parent=styles["Title"], fontSize=16, spaceAfter=6, textColor="#0F172A")
        sub_style = ParagraphStyle("CustomSub", parent=styles["Normal"], fontSize=9, textColor="#64748B", spaceAfter=12)
        heading_style = ParagraphStyle("CustomH", parent=styles["Heading2"], fontSize=12, textColor="#0F172A", spaceBefore=14, spaceAfter=6)
        body_style = ParagraphStyle("CustomBody", parent=styles["Normal"], fontSize=10, leading=15, textColor="#334155", spaceAfter=4)
        footer_style = ParagraphStyle("CustomFooter", parent=styles["Normal"], fontSize=7, textColor="#94A3B8", spaceBefore=20, spaceAfter=4)

        elements = []
        elements.append(Paragraph(f"DocuAction — {action_type.title()} Report", title_style))
        elements.append(Paragraph(f"Generated: {datetime.utcnow().strftime('%B %d, %Y %H:%M UTC')}", sub_style))
        if model:
            elements.append(Paragraph(f"Model: {model} | Confidence: {int(confidence * 100)}%", sub_style))
        elements.append(Spacer(1, 12))

        for line in text.split("\n"):
            line = line.strip()
            if not line:
                elements.append(Spacer(1, 6))
            elif line.startswith("==="):
                continue
            elif line.startswith("---"):
                continue
            elif line == line.upper() and len(line) > 3 and not line.startswith("[") and not line.startswith("Generated") and not line.startswith("Model"):
                elements.append(Paragraph(line, heading_style))
            else:
                # Escape HTML chars
                safe = line.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                elements.append(Paragraph(safe, body_style))

        elements.append(Spacer(1, 20))
        elements.append(Paragraph(DISCLOSURE, footer_style))

        doc.build(elements)
        buf.seek(0)
        return buf
    except ImportError:
        # ReportLab not available — return text as PDF-like
        buf = io.BytesIO(text.encode("utf-8"))
        return buf


def _build_docx(text, action_type, model="", confidence=0):
    """Generate DOCX from formatted text using python-docx."""
    try:
        from docx import Document as DocxDocument
        from docx.shared import Pt, Inches, RGBColor
        from docx.enum.text import WD_ALIGN_PARAGRAPH

        doc = DocxDocument()

        # Title
        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.LEFT
        run = p.add_run(f"DocuAction — {action_type.title()} Report")
        run.bold = True
        run.font.size = Pt(16)
        run.font.color.rgb = RGBColor(0x0F, 0x17, 0x2A)

        # Subtitle
        p = doc.add_paragraph()
        run = p.add_run(f"Generated: {datetime.utcnow().strftime('%B %d, %Y %H:%M UTC')}")
        run.font.size = Pt(9)
        run.font.color.rgb = RGBColor(0x64, 0x74, 0x8B)
        if model:
            p = doc.add_paragraph()
            run = p.add_run(f"Model: {model} | Confidence: {int(confidence * 100)}%")
            run.font.size = Pt(9)
            run.font.color.rgb = RGBColor(0x64, 0x74, 0x8B)

        for line in text.split("\n"):
            line = line.strip()
            if not line:
                doc.add_paragraph("")
            elif line.startswith("==="):
                continue
            elif line.startswith("---"):
                continue
            elif line == line.upper() and len(line) > 3 and not line.startswith("[") and not line.startswith("Generated") and not line.startswith("Model"):
                p = doc.add_paragraph()
                run = p.add_run(line)
                run.bold = True
                run.font.size = Pt(12)
                run.font.color.rgb = RGBColor(0x0F, 0x17, 0x2A)
            else:
                p = doc.add_paragraph()
                run = p.add_run(line)
                run.font.size = Pt(10)
                run.font.color.rgb = RGBColor(0x33, 0x41, 0x55)

        # Disclosure
        doc.add_paragraph("")
        p = doc.add_paragraph()
        run = p.add_run(DISCLOSURE)
        run.font.size = Pt(7)
        run.font.color.rgb = RGBColor(0x94, 0xA3, 0xB8)

        buf = io.BytesIO()
        doc.save(buf)
        buf.seek(0)
        return buf
    except ImportError:
        buf = io.BytesIO(text.encode("utf-8"))
        return buf


@router.get("/api/export/{output_id}/{format}")
async def export_output(
    output_id: str,
    format: str,
    db: AsyncSession = Depends(get_db),
    user=Depends(get_current_user),
):
    """Export an intelligence output as PDF, DOCX, or TXT. Never shows raw JSON."""
    from app.models.database import Output

    result = await db.execute(select(Output).where(Output.id == output_id))
    output = result.scalar_one_or_none()

    if not output:
        raise HTTPException(404, "Output not found")

    # Parse content
    data = _parse_content(output.content)
    action_type = output.action_type or "output"
    model = output.model_used or ""
    confidence = output.confidence or 0

    # Format into readable text
    text = _format_text(data, action_type, model, confidence)

    if format == "txt":
        buf = io.BytesIO(text.encode("utf-8"))
        return StreamingResponse(buf, media_type="text/plain", headers={"Content-Disposition": f"attachment; filename=DocuAction_{action_type}.txt"})

    elif format == "pdf":
        buf = _build_pdf(text, action_type, model, confidence)
        return StreamingResponse(buf, media_type="application/pdf", headers={"Content-Disposition": f"attachment; filename=DocuAction_{action_type}.pdf"})

    elif format == "docx":
        buf = _build_docx(text, action_type, model, confidence)
        return StreamingResponse(buf, media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document", headers={"Content-Disposition": f"attachment; filename=DocuAction_{action_type}.docx"})

    else:
        raise HTTPException(400, f"Unsupported format: {format}. Use pdf, docx, or txt.")
