"""
Export System — Server-Side Document Generation
Generates PDF, DOCX, and TXT exports from AI outputs.

All exports include mandatory AI disclosure footer:
"Generated by DocuAction AI – AI-generated content. Review recommended before use."

PDF generated server-side using ReportLab (no client-side generation).
DOCX generated using python-docx.
"""
import io
import json
import logging
from datetime import datetime
from typing import Optional
from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select

from app.core.database import get_db
from app.core.security import get_current_user
from app.models.database import Output, Document
from app.services.ai_disclosure import DISCLOSURE_LABEL, get_pdf_footer

logger = logging.getLogger("docuaction.export")
router = APIRouter(prefix="/api/export", tags=["Export"])

DISCLOSURE_TEXT = "Generated by DocuAction AI – AI-generated content. Review recommended before use."


def _parse_output_content(output) -> dict:
    """Parse the JSON content from an output record."""
    try:
        if isinstance(output.content, str):
            return json.loads(output.content)
        return output.content or {}
    except (json.JSONDecodeError, TypeError):
        return {"raw": output.content or "No content"}


# ═══ PDF EXPORT ═══

@router.get("/{output_id}/pdf")
async def export_pdf(
    output_id: str,
    template: str = "default",
    db: AsyncSession = Depends(get_db),
    user=Depends(get_current_user),
):
    """
    Export AI output as PDF. Server-side generation using ReportLab.
    Includes mandatory AI disclosure footer on every page.
    """
    result = await db.execute(
        select(Output).where(Output.id == output_id, Output.user_id == user.id)
    )
    output = result.scalar_one_or_none()
    if not output:
        raise HTTPException(404, "Output not found")

    content = _parse_output_content(output)

    # Get document name
    doc_result = await db.execute(select(Document).where(Document.id == output.document_id))
    doc = doc_result.scalar_one_or_none()
    doc_name = doc.filename if doc else "Unknown Document"

    try:
        from reportlab.lib.pagesizes import letter
        from reportlab.lib.units import inch
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.colors import HexColor
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
        from reportlab.lib.enums import TA_LEFT, TA_CENTER

        buffer = io.BytesIO()
        doc_pdf = SimpleDocTemplate(buffer, pagesize=letter, topMargin=0.75*inch, bottomMargin=1.2*inch)

        styles = getSampleStyleSheet()
        styles.add(ParagraphStyle(name='DocTitle', fontSize=18, spaceAfter=12, textColor=HexColor('#0B3C5D'), fontName='Helvetica-Bold'))
        styles.add(ParagraphStyle(name='SectionHead', fontSize=13, spaceAfter=8, spaceBefore=16, textColor=HexColor('#0B3C5D'), fontName='Helvetica-Bold'))
        styles.add(ParagraphStyle(name='Body', fontSize=10, spaceAfter=6, leading=14, fontName='Helvetica'))
        styles.add(ParagraphStyle(name='Disclosure', fontSize=7, textColor=HexColor('#666666'), fontName='Helvetica-Oblique', alignment=TA_CENTER))
        styles.add(ParagraphStyle(name='Meta', fontSize=8, textColor=HexColor('#999999'), fontName='Helvetica'))

        elements = []

        # Title
        elements.append(Paragraph(f"DocuAction AI — {output.action_type.title()} Report", styles['DocTitle']))
        elements.append(Paragraph(f"Source: {doc_name}", styles['Meta']))
        elements.append(Paragraph(f"Generated: {datetime.utcnow().strftime('%B %d, %Y %H:%M UTC')}", styles['Meta']))
        elements.append(Paragraph(f"Model: {output.model_used or 'N/A'} | Confidence: {int((output.confidence or 0) * 100)}%", styles['Meta']))
        elements.append(Spacer(1, 20))

        # Content based on action type
        if output.action_type == "summary":
            summary_text = content.get("summary", "No summary available")
            elements.append(Paragraph("Executive Summary", styles['SectionHead']))
            elements.append(Paragraph(summary_text, styles['Body']))

            metrics = content.get("key_metrics", [])
            if metrics:
                elements.append(Spacer(1, 10))
                elements.append(Paragraph("Key Metrics", styles['SectionHead']))
                for m in metrics:
                    if isinstance(m, dict):
                        elements.append(Paragraph(f"• {m.get('metric', '')}: {m.get('value', '')} — {m.get('context', '')}", styles['Body']))

            recs = content.get("recommendations", [])
            if recs:
                elements.append(Spacer(1, 10))
                elements.append(Paragraph("Recommendations", styles['SectionHead']))
                for i, r in enumerate(recs, 1):
                    elements.append(Paragraph(f"{i}. {r}", styles['Body']))

        elif output.action_type == "actions":
            tasks = content.get("tasks", [])
            if tasks:
                elements.append(Paragraph("Action Items", styles['SectionHead']))
                for t in tasks:
                    if isinstance(t, dict):
                        elements.append(Paragraph(
                            f"• [{t.get('priority', 'medium').upper()}] {t.get('task', '')} — Owner: {t.get('owner', 'TBD')} | Deadline: {t.get('deadline', 'TBD')}",
                            styles['Body']
                        ))

            decisions = content.get("decisions", [])
            if decisions:
                elements.append(Spacer(1, 10))
                elements.append(Paragraph("Decisions", styles['SectionHead']))
                for d in decisions:
                    if isinstance(d, dict):
                        elements.append(Paragraph(f"• {d.get('decision', '')} — By: {d.get('decided_by', 'Unknown')}", styles['Body']))

            follow_ups = content.get("follow_ups", [])
            if follow_ups:
                elements.append(Spacer(1, 10))
                elements.append(Paragraph("Follow-Ups", styles['SectionHead']))
                for f in follow_ups:
                    if isinstance(f, dict):
                        elements.append(Paragraph(f"• {f.get('item', '')} — Owner: {f.get('owner', 'TBD')} | Due: {f.get('due', 'TBD')}", styles['Body']))

        elif output.action_type == "insights":
            insights = content.get("insights", [])
            if insights:
                elements.append(Paragraph("Key Insights", styles['SectionHead']))
                for ins in insights:
                    if isinstance(ins, dict):
                        elements.append(Paragraph(
                            f"• [{ins.get('impact', 'medium').upper()}] {ins.get('finding', '')}",
                            styles['Body']
                        ))
                        if ins.get('recommendation'):
                            elements.append(Paragraph(f"  Recommendation: {ins.get('recommendation')}", styles['Body']))

        elif output.action_type == "email":
            elements.append(Paragraph(f"Subject: {content.get('subject', 'N/A')}", styles['SectionHead']))
            elements.append(Paragraph(f"To: {content.get('to', 'N/A')}", styles['Meta']))
            elements.append(Spacer(1, 10))
            body = content.get("body", "No email body")
            for para in body.split("\n"):
                if para.strip():
                    elements.append(Paragraph(para, styles['Body']))

        elif output.action_type == "brief":
            elements.append(Paragraph(content.get("title", "Executive Brief"), styles['SectionHead']))
            elements.append(Paragraph(f"Situation: {content.get('situation', 'N/A')}", styles['Body']))
            findings = content.get("key_findings", [])
            if findings:
                elements.append(Paragraph("Key Findings", styles['SectionHead']))
                for f in findings:
                    if isinstance(f, dict):
                        elements.append(Paragraph(f"• {f.get('finding', '')} — {f.get('data', '')}", styles['Body']))
            if content.get("decision_required"):
                elements.append(Spacer(1, 10))
                elements.append(Paragraph(f"Decision Required: {content.get('decision_required')}", styles['SectionHead']))
                elements.append(Paragraph(f"Recommendation: {content.get('recommendation', 'N/A')}", styles['Body']))

        else:
            elements.append(Paragraph("Output", styles['SectionHead']))
            elements.append(Paragraph(json.dumps(content, indent=2), styles['Body']))

        # Mandatory AI Disclosure Footer
        elements.append(Spacer(1, 30))
        elements.append(Paragraph("─" * 80, styles['Disclosure']))
        elements.append(Paragraph(DISCLOSURE_TEXT, styles['Disclosure']))
        elements.append(Paragraph(
            f"Platform: DocuAction AI v3.3.0 | Provider: Alliance Global Tech, Inc. | "
            f"Model: {output.model_used or 'N/A'} | Confidence: {int((output.confidence or 0) * 100)}%",
            styles['Disclosure']
        ))
        elements.append(Paragraph(
            "Utah AI Policy Act (SB 149) | Colorado AI Act (SB 205) | EU AI Act Article 50",
            styles['Disclosure']
        ))

        doc_pdf.build(elements)
        buffer.seek(0)

        filename = f"DocuAction_{output.action_type}_{datetime.utcnow().strftime('%Y%m%d')}.pdf"
        return StreamingResponse(
            buffer,
            media_type="application/pdf",
            headers={"Content-Disposition": f"attachment; filename={filename}"}
        )

    except ImportError:
        raise HTTPException(500, "PDF generation requires reportlab. Install: pip install reportlab")


# ═══ DOCX EXPORT ═══

@router.get("/{output_id}/docx")
async def export_docx(
    output_id: str,
    template: str = "default",
    db: AsyncSession = Depends(get_db),
    user=Depends(get_current_user),
):
    """Export AI output as Word document with AI disclosure footer."""
    result = await db.execute(
        select(Output).where(Output.id == output_id, Output.user_id == user.id)
    )
    output = result.scalar_one_or_none()
    if not output:
        raise HTTPException(404, "Output not found")

    content = _parse_output_content(output)

    try:
        from docx import Document as DocxDocument
        from docx.shared import Inches, Pt, RGBColor
        from docx.enum.text import WD_ALIGN_PARAGRAPH

        doc = DocxDocument()

        # Title
        title = doc.add_heading(f"DocuAction AI — {output.action_type.title()} Report", level=1)
        for run in title.runs:
            run.font.color.rgb = RGBColor(0x0B, 0x3C, 0x5D)

        doc.add_paragraph(f"Generated: {datetime.utcnow().strftime('%B %d, %Y %H:%M UTC')}")
        doc.add_paragraph(f"Model: {output.model_used or 'N/A'} | Confidence: {int((output.confidence or 0) * 100)}%")
        doc.add_paragraph("")

        # Content
        if output.action_type == "summary":
            doc.add_heading("Executive Summary", level=2)
            doc.add_paragraph(content.get("summary", "No summary"))
            for m in content.get("key_metrics", []):
                if isinstance(m, dict):
                    doc.add_paragraph(f"{m.get('metric', '')}: {m.get('value', '')} — {m.get('context', '')}", style='List Bullet')
            if content.get("recommendations"):
                doc.add_heading("Recommendations", level=2)
                for r in content.get("recommendations", []):
                    doc.add_paragraph(r, style='List Number')

        elif output.action_type == "actions":
            for section, key in [("Action Items", "tasks"), ("Decisions", "decisions"), ("Follow-Ups", "follow_ups")]:
                items = content.get(key, [])
                if items:
                    doc.add_heading(section, level=2)
                    for item in items:
                        if isinstance(item, dict):
                            text = item.get("task") or item.get("decision") or item.get("item") or str(item)
                            doc.add_paragraph(text, style='List Bullet')

        else:
            doc.add_heading("Output", level=2)
            doc.add_paragraph(json.dumps(content, indent=2))

        # Mandatory AI Disclosure
        doc.add_paragraph("")
        doc.add_paragraph("─" * 50)
        disclaimer = doc.add_paragraph(DISCLOSURE_TEXT)
        disclaimer.alignment = WD_ALIGN_PARAGRAPH.CENTER
        for run in disclaimer.runs:
            run.font.size = Pt(8)
            run.font.color.rgb = RGBColor(0x99, 0x99, 0x99)

        buffer = io.BytesIO()
        doc.save(buffer)
        buffer.seek(0)

        filename = f"DocuAction_{output.action_type}_{datetime.utcnow().strftime('%Y%m%d')}.docx"
        return StreamingResponse(
            buffer,
            media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            headers={"Content-Disposition": f"attachment; filename={filename}"}
        )

    except ImportError:
        raise HTTPException(500, "DOCX generation requires python-docx")


# ═══ TEXT EXPORT ═══

@router.get("/{output_id}/txt")
async def export_txt(
    output_id: str,
    db: AsyncSession = Depends(get_db),
    user=Depends(get_current_user),
):
    """Export AI output as plain text with AI disclosure footer."""
    result = await db.execute(
        select(Output).where(Output.id == output_id, Output.user_id == user.id)
    )
    output = result.scalar_one_or_none()
    if not output:
        raise HTTPException(404, "Output not found")

    content = _parse_output_content(output)

    lines = [
        f"DocuAction AI — {output.action_type.title()} Report",
        f"Generated: {datetime.utcnow().strftime('%B %d, %Y %H:%M UTC')}",
        f"Model: {output.model_used or 'N/A'} | Confidence: {int((output.confidence or 0) * 100)}%",
        "",
        "=" * 60,
        "",
    ]

    # Format content
    if output.action_type == "summary":
        lines.append("EXECUTIVE SUMMARY")
        lines.append("-" * 40)
        lines.append(content.get("summary", "No summary"))
    elif output.action_type == "actions":
        for section, key in [("ACTION ITEMS", "tasks"), ("DECISIONS", "decisions"), ("FOLLOW-UPS", "follow_ups")]:
            items = content.get(key, [])
            if items:
                lines.append(f"\n{section}")
                lines.append("-" * 40)
                for item in items:
                    if isinstance(item, dict):
                        text = item.get("task") or item.get("decision") or item.get("item") or str(item)
                        lines.append(f"  • {text}")
    else:
        lines.append(json.dumps(content, indent=2))

    # Mandatory AI Disclosure
    lines.extend([
        "",
        "=" * 60,
        DISCLOSURE_TEXT,
        f"Platform: DocuAction AI v3.3.0 | Alliance Global Tech, Inc.",
        "Utah AI Policy Act (SB 149) | Colorado AI Act (SB 205)",
        "=" * 60,
    ])

    text_content = "\n".join(lines)
    buffer = io.BytesIO(text_content.encode("utf-8"))

    filename = f"DocuAction_{output.action_type}_{datetime.utcnow().strftime('%Y%m%d')}.txt"
    return StreamingResponse(
        buffer,
        media_type="text/plain",
        headers={"Content-Disposition": f"attachment; filename={filename}"}
    )
