"""
Intelligence Output Persistence & Auto-Processing
- Auto-generates all 5 outputs on upload
- Stores in database
- Returns stored outputs without reprocessing
- Lists all historical outputs
"""
import uuid
import logging
from datetime import datetime
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, desc

from app.core.database import get_db
from app.core.security import get_current_user

logger = logging.getLogger("docuaction.intelligence")
router = APIRouter(tags=["Intelligence Outputs"])


@router.get("/api/intelligence/outputs")
async def list_all_outputs(
    db: AsyncSession = Depends(get_db),
    user=Depends(get_current_user),
):
    """List all stored intelligence outputs for the current user."""
    from app.models.database import Output, Document

    results = await db.execute(
        select(Output)
        .where(Output.user_id == user.id)
        .order_by(desc(Output.created_at))
        .limit(100)
    )
    outputs = results.scalars().all()

    # Group by document
    doc_ids = set(o.document_id for o in outputs if o.document_id)
    doc_map = {}
    if doc_ids:
        docs = await db.execute(select(Document).where(Document.id.in_(doc_ids)))
        for d in docs.scalars().all():
            doc_map[str(d.id)] = d.filename

    grouped = {}
    for o in outputs:
        doc_id = str(o.document_id) if o.document_id else "unknown"
        if doc_id not in grouped:
            grouped[doc_id] = {
                "document_id": doc_id,
                "document_name": doc_map.get(doc_id, "Unknown Document"),
                "outputs": {},
                "last_generated": None,
                "correlation_id": "DA-" + uuid.uuid4().hex[:4].upper() + "-" + uuid.uuid4().hex[:4].upper(),
            }

        action = o.action_type or "output"
        grouped[doc_id]["outputs"][action] = {
            "id": str(o.id),
            "action_type": action,
            "confidence": o.confidence or 0,
            "model_used": o.model_used or "",
            "processing_time_ms": o.processing_time_ms or 0,
            "created_at": o.created_at.isoformat() if o.created_at else None,
            "status": "ready",
        }

        if o.created_at:
            ts = o.created_at.isoformat()
            if not grouped[doc_id]["last_generated"] or ts > grouped[doc_id]["last_generated"]:
                grouped[doc_id]["last_generated"] = ts

    return {
        "total_outputs": len(outputs),
        "total_documents": len(grouped),
        "documents": list(grouped.values()),
    }


@router.get("/api/intelligence/outputs/{output_id}")
async def get_stored_output(
    output_id: str,
    db: AsyncSession = Depends(get_db),
    user=Depends(get_current_user),
):
    """Retrieve a single stored output — no reprocessing."""
    from app.models.database import Output
    import json

    result = await db.execute(
        select(Output).where(Output.id == output_id, Output.user_id == user.id)
    )
    output = result.scalar_one_or_none()
    if not output:
        raise HTTPException(404, "Output not found")

    content = output.content
    if isinstance(content, str):
        try:
            content = json.loads(content)
        except (json.JSONDecodeError, TypeError):
            content = {"text": content}

    return {
        "id": str(output.id),
        "document_id": str(output.document_id) if output.document_id else None,
        "action_type": output.action_type,
        "content": content,
        "confidence": output.confidence or 0,
        "model_used": output.model_used or "",
        "processing_time_ms": output.processing_time_ms or 0,
        "created_at": output.created_at.isoformat() if output.created_at else None,
        "status": "ready",
        "correlation_id": "DA-" + uuid.uuid4().hex[:4].upper() + "-" + uuid.uuid4().hex[:4].upper(),
        "disclosure": {
            "label": "Generated by DocuAction Intelligence Pipeline. Human review required.",
            "model": output.model_used or "pipeline",
            "confidence_percent": int((output.confidence or 0) * 100),
            "removable": False,
        },
    }


@router.get("/api/intelligence/document/{document_id}")
async def get_document_outputs(
    document_id: str,
    db: AsyncSession = Depends(get_db),
    user=Depends(get_current_user),
):
    """Get all stored outputs for a specific document — no reprocessing."""
    from app.models.database import Output, Document
    import json

    # Get document info
    doc_result = await db.execute(select(Document).where(Document.id == document_id))
    doc = doc_result.scalar_one_or_none()

    # Get all outputs for this document
    results = await db.execute(
        select(Output)
        .where(Output.document_id == document_id, Output.user_id == user.id)
        .order_by(desc(Output.created_at))
    )
    outputs = results.scalars().all()

    output_map = {}
    for o in outputs:
        action = o.action_type or "output"
        if action not in output_map:  # Keep latest only
            content = o.content
            if isinstance(content, str):
                try:
                    content = json.loads(content)
                except:
                    content = {"text": content}

            output_map[action] = {
                "id": str(o.id),
                "action_type": action,
                "content": content,
                "confidence": o.confidence or 0,
                "model_used": o.model_used or "",
                "processing_time_ms": o.processing_time_ms or 0,
                "created_at": o.created_at.isoformat() if o.created_at else None,
            }

    return {
        "document_id": document_id,
        "document_name": doc.filename if doc else "Unknown",
        "document_status": doc.status if doc else "unknown",
        "outputs_available": list(output_map.keys()),
        "outputs_count": len(output_map),
        "outputs": output_map,
        "all_generated": len(output_map) >= 5,
        "correlation_id": "DA-" + uuid.uuid4().hex[:4].upper() + "-" + uuid.uuid4().hex[:4].upper(),
    }


@router.post("/api/intelligence/auto-process/{document_id}")
async def auto_process_document(
    document_id: str,
    db: AsyncSession = Depends(get_db),
    user=Depends(get_current_user),
):
    """
    Auto-generate ALL 5 output types for a document.
    Skips any output type that already exists (no reprocessing).
    """
    from app.models.database import Output, Document
    from app.services.ai_engine import process_document
    import json

    # Check document exists
    doc_result = await db.execute(select(Document).where(Document.id == document_id))
    doc = doc_result.scalar_one_or_none()
    if not doc:
        raise HTTPException(404, "Document not found")

    # Check existing outputs
    existing = await db.execute(
        select(Output).where(Output.document_id == document_id, Output.user_id == user.id)
    )
    existing_types = set(o.action_type for o in existing.scalars().all())

    # Generate missing outputs
    all_types = ["summary", "actions", "insights", "email", "brief"]
    generated = []
    skipped = []

    for action_type in all_types:
        if action_type in existing_types:
            skipped.append(action_type)
            continue

        try:
            result = await process_document(doc, action_type)

            output = Output(
                user_id=user.id,
                document_id=doc.id,
                tenant_id=getattr(user, 'tenant_id', 'default') or 'default',
                action_type=action_type,
                content=json.dumps(result) if isinstance(result, dict) else str(result),
                confidence=result.get("confidence", 0) if isinstance(result, dict) else 0,
                model_used=result.get("model_used", "") if isinstance(result, dict) else "",
                processing_time_ms=result.get("processing_time_ms", 0) if isinstance(result, dict) else 0,
            )
            db.add(output)
            await db.flush()
            generated.append(action_type)

            # Auto-queue for validation if needed
            try:
                from app.api.validation_routes import auto_queue_output
                conf = result.get("confidence", 0) if isinstance(result, dict) else 0
                preview = result.get("summary", "")[:300] if isinstance(result, dict) else ""
                await auto_queue_output(
                    db=db, user_id=str(user.id),
                    tenant_id=getattr(user, 'tenant_id', 'default') or 'default',
                    document_id=str(doc.id), document_name=doc.filename,
                    output_id=str(output.id), action_type=action_type,
                    confidence=conf, content_preview=preview,
                )
            except Exception:
                pass
        except Exception as e:
            logger.error(f"Auto-process {action_type} failed: {e}")

    if generated:
        doc.status = "processed"
        await db.commit()

    return {
        "document_id": document_id,
        "generated": generated,
        "skipped": skipped,
        "total_ready": len(generated) + len(skipped),
        "all_complete": len(generated) + len(skipped) >= 5,
        "status": "complete" if len(generated) + len(skipped) >= 5 else "partial",
    }
