"""
TEFCA registry seed — Phase 1C (baseline dataset) + Phase 1D (36 defects).

Generates a synthetic-but-realistic TEFCA registry:
  * 11 QHINs (REAL org names; SYNTHETIC identifiers + FHIR JSON)
  * ~45 Participants (3-5 per QHIN, one QHIN intentionally empty)
  * ~120 Sub-Participants (2-4 per Participant)
  * identifiers (TEFCAID + HCID on every entity; NPI ~85%; CCN/CLIA/NAIC subsets)
  * one initial tefca_entity_versions snapshot per entity
  * relationships (belongs_to / sub_participant_of + dual / historical / merger)
  * FHIR R4 Organization JSON in fhir_resource (TEFCA QHIN profile for QHINs)
  * 36 INTENTIONAL defects woven into the dataset (Phase 1D)

Safety
------
ALL identifiers are synthetic. NPIs live in the obviously-fake ``1234xxxxx`` block
(with a valid NPI Luhn check digit unless a defect requires otherwise). No real
NPI / TEFCAID / HCID values are used.

Idempotency
-----------
Every row uses a deterministic ``uuid5`` id derived from a stable natural key, and
all pseudo-random choices come from a fixed-seed RNG driven in a fixed loop order,
so the generated data is byte-stable across runs. Rows are written with
``INSERT ... ON CONFLICT (id) DO UPDATE``.

Defects are LATENT data problems only — no verification jobs / checks / findings
are created here (those stay at 0; discovery is a later phase). Each defect is
documented in ``docs/tefca/TEFCA_DEFECT_SCENARIOS.md`` (regenerated by this script).

Run: ``python -m app.tefca_registry.seed``
"""
from __future__ import annotations

import asyncio
import datetime as dt
import logging
import os
import random
import uuid

from sqlalchemy import func, select
from sqlalchemy.dialects.postgresql import insert as pg_insert

from app.core.database import Base, async_session_maker, engine
from app.tefca_registry import models as r

logger = logging.getLogger("docuaction.tefca_registry.seed")

# Deterministic namespaces / seed.
_NS = uuid.UUID("2c6f1e40-7b3a-5d21-9e88-4a1c0b7e5f30")
_SEED = 20260725


def _id(kind: str, key: str) -> uuid.UUID:
    return uuid.uuid5(_NS, f"{kind}:{key}")


# System URIs per identifier type (from spec).
SYSTEM_URI = {
    "npi": "http://hl7.org/fhir/sid/us-npi",
    "hcid": "urn:ietf:rfc:3986",
    "ccn": "urn:oid:2.16.840.1.113883.4.336",
    "clia": "urn:oid:2.16.840.1.113883.4.7",
    "naic": "urn:oid:2.16.840.1.113883.6.300",
    "tefcaid": "urn:docuaction:tefca/fhir/identifier/tefcaid",
}
QHIN_PROFILE = "urn:docuaction:tefca/fhir/StructureDefinition/qhin-organization"

EXPECTED = {
    "tefca_reg_entities": 176,
    "tefca_entity_identifiers": 350,   # >= (target says ~350+)
    "tefca_entity_relationships": 180,  # >= (~180+)
    "tefca_entity_versions": 176,
    "tefca_entity_endpoints": 20,       # >= (~20+)
    "tefca_verification_jobs": 0,
    "tefca_verification_checks": 0,
    "tefca_entity_findings": 0,
    "tefca_import_batches": 0,
    "tefca_reg_audit_log": 0,
}
# Tables whose expected count is a floor (>=) rather than exact.
_FLOOR = {"tefca_entity_identifiers", "tefca_entity_relationships", "tefca_entity_endpoints"}
# entities/versions are "~"; allow a small tolerance for the extra HR-011 child.
_TOLERANCE = {"tefca_reg_entities": 6, "tefca_entity_versions": 6}


# ══════════════════════════════════════════════════════════════════════════════
# NPI Luhn helpers (NPI uses the Luhn algorithm over "80840" + 9-digit base)
# ══════════════════════════════════════════════════════════════════════════════

def _npi_check_digit(nine: str) -> int:
    s = "80840" + nine
    total = 0
    for i, ch in enumerate(reversed(s)):
        d = int(ch)
        if i % 2 == 0:
            d *= 2
            if d > 9:
                d -= 9
        total += d
    return (10 - (total % 10)) % 10


def _npi(nine: str, *, valid: bool = True) -> str:
    """10-digit synthetic NPI from a 9-digit base. valid=False breaks the Luhn."""
    cd = _npi_check_digit(nine)
    if not valid:
        cd = (cd + 1) % 10
    return nine + str(cd)


# ══════════════════════════════════════════════════════════════════════════════
# QHIN definitions (real names, synthetic everything else)
# ══════════════════════════════════════════════════════════════════════════════

# (key, name, state, designation_date, operational_status, verification_status)
QHINS = [
    ("commonwell", "CommonWell Health Alliance", "VA", dt.date(2023, 12, 12), "active", "verified"),
    ("ehealthexchange", "eHealth Exchange", "VA", dt.date(2023, 12, 12), "active", "verified"),
    ("epicnexus", "Epic Nexus", "WI", dt.date(2023, 12, 12), "active", "verified"),
    ("healthgorilla", "Health Gorilla", "CA", dt.date(2023, 12, 12), "active", "verified"),
    ("kno2", "Kno2", "ID", dt.date(2023, 12, 12), "active", "verified"),
    ("konza", "KONZA National Network", "KS", dt.date(2023, 12, 12), "active", "verified"),
    ("medallies", "MedAllies", "NY", dt.date(2023, 12, 12), "active", "verified"),
    ("eclinicalworks", "eClinicalWorks", "MA", dt.date(2025, 1, 16), "active", "verified"),
    ("surescripts", "Surescripts", "VA", dt.date(2025, 4, 15), "active", "verified"),
    ("netsmart", "Netsmart", "KS", dt.date(2025, 8, 5), "active", "not_verified"),
    ("oraclehealth", "Oracle Health", "TX", dt.date(2025, 11, 20), "active", "in_review"),
]
# Oracle Health intentionally has ZERO participants (DEF-HR-006).
ZERO_PARTICIPANT_QHIN = "oraclehealth"

# Name-generation pools (synthetic).
_ADJ = ["Summit", "Riverbend", "Cascade", "Granite", "Harbor", "Prairie", "Cypress",
        "Sterling", "Meridian", "Beacon", "Cardinal", "Evergreen", "Highland",
        "Lakeshore", "Northgate", "Pinnacle", "Silverton", "Brookfield", "Fairview",
        "Ironwood", "Crestline", "Willowbrook", "Redwood", "Clearwater", "Stonebridge"]
_NOUN = ["Valley", "Peak", "Grove", "Ridge", "Bay", "Delta", "Point", "Crossing",
         "Springs", "Field", "Park", "Landing", "Heights", "Harbor", "Hollow"]
_CITY = ["Fairview", "Springfield", "Riverside", "Georgetown", "Franklin", "Clinton",
         "Madison", "Salem", "Auburn", "Bristol", "Milton", "Newport", "Ashland",
         "Kingston", "Oxford", "Dover", "Concord", "Marion", "Dayton", "Arlington"]
_COUNTY = ["Jefferson", "Lincoln", "Washington", "Franklin", "Jackson", "Madison",
           "Marion", "Monroe", "Clay", "Union", "Grant", "Wayne"]

# Participant entity types (varied, geographically neutral).
_PART_TYPES = [
    "hospital_system", "health_plan", "health_information_exchange", "provider",
    "clearinghouse", "vendor", "government_agency", "laboratory",
]
# Sub-participant flavors: (name suffix, entity_type)
_SUB_KINDS = [
    ("Family Clinic", "provider"),
    ("Diagnostic Laboratory", "laboratory"),
    ("Urgent Care", "provider"),
    ("Imaging Center", "provider"),
    ("Community Pharmacy", "pharmacy"),
    ("Behavioral Health", "provider"),
]
# States roughly spread across regions for participants.
_STATES = ["CA", "TX", "NY", "FL", "IL", "PA", "OH", "GA", "NC", "MI", "WA", "AZ",
           "MA", "TN", "IN", "MO", "MD", "WI", "CO", "MN", "KS", "ID", "VA", "OR"]


# ══════════════════════════════════════════════════════════════════════════════
# Generator
# ══════════════════════════════════════════════════════════════════════════════

class _Gen:
    """Builds all rows in memory, applies the 36 defects, then exposes row lists."""

    def __init__(self):
        self.rng = random.Random(_SEED)
        self.entities: list[dict] = []
        self.identifiers: list[dict] = []
        self.relationships: list[dict] = []
        self.endpoints: list[dict] = []
        self.versions: list[dict] = []
        self.by_key: dict[str, dict] = {}
        self.children_of: dict[str, list[str]] = {}   # parent key -> child keys
        self.qhin_of: dict[str, str] = {}             # entity key -> qhin key
        self._npi_seq = 0
        self._tefca_seq = 0
        self._hcid_seq = 0
        self._ccn_seq = 0
        self._clia_seq = 0
        self._naic_seq = 0
        self.defects: list[dict] = []                 # concrete defect records for the doc

    # ---- id issuers -----------------------------------------------------------
    def next_tefcaid(self):
        self._tefca_seq += 1
        return f"TEFCA-{self._tefca_seq:06d}"

    def next_hcid(self):
        self._hcid_seq += 1
        return f"2.16.840.1.113883.3.9999.{self._hcid_seq:05d}"

    def next_npi(self, *, valid=True):
        self._npi_seq += 1
        return _npi(f"1234{self._npi_seq:05d}", valid=valid)

    def next_ccn(self):
        self._ccn_seq += 1
        return f"99{self._ccn_seq:04d}"

    def next_clia(self):
        self._clia_seq += 1
        return f"99D{self._clia_seq:07d}"

    def next_naic(self):
        self._naic_seq += 1
        return f"99{self._naic_seq:03d}"

    # ---- entity + identifier builders -----------------------------------------
    def add_entity(self, key, name, level, etype, state, *, op_status="active",
                   ver_status="verified", designation_date=None, onboarding_date=None,
                   is_active=True, purposes=None):
        city = self.rng.choice(_CITY)
        ent = dict(
            key=key,
            id=_id("entity", key),
            name=name,
            display_name=name,
            entity_level=level,
            entity_type=etype,
            operational_status=op_status,
            verification_status=ver_status,
            state=state,
            address=f"{self.rng.randint(100, 9899)} {self.rng.choice(_NOUN)} St",
            city=city,
            zip=f"{self.rng.randint(10000, 99999):05d}",
            county=f"{self.rng.choice(_COUNTY)} County",
            designation_date=designation_date,
            onboarding_date=onboarding_date,
            fhir_resource=None,           # filled after identifiers/relationships
            exchange_purposes={"purposes": purposes or ["treatment", "healthcare_operations"]},
            current_version=1,
            is_active=is_active,
        )
        self.entities.append(ent)
        self.by_key[key] = ent
        return ent

    def add_identifier(self, entity_key, itype, value, *, system_uri="_default",
                       is_primary=False, status="active", effective=None, end=None,
                       tag=None):
        uri = SYSTEM_URI.get(itype) if system_uri == "_default" else system_uri
        # unique id incorporates a tag so a defect can add a duplicate value row.
        idkey = f"{entity_key}:{itype}:{tag or value}"
        row = dict(
            id=_id("ident", idkey),
            entity_id=self.by_key[entity_key]["id"],
            identifier_type=itype,
            identifier_value=value,
            system_uri=uri,
            is_primary=is_primary,
            identifier_status=status,
            effective_date=effective,
            end_date=end,
        )
        self.identifiers.append(row)
        return row

    def add_relationship(self, parent_key, child_key, rtype, effective, *,
                         end=None, status="active", source="import", notes=None,
                         tag=""):
        relkey = f"{parent_key}->{child_key}:{rtype}:{effective.isoformat()}:{tag}"
        row = dict(
            id=_id("rel", relkey),
            parent_entity_id=self.by_key[parent_key]["id"],
            child_entity_id=self.by_key[child_key]["id"],
            relationship_type=rtype,
            effective_date=effective,
            end_date=end,
            status=status,
            source=source,
            notes=notes,
        )
        self.relationships.append(row)
        return row

    def add_endpoint(self, entity_key, etype="fhir_r4"):
        ent = self.by_key[entity_key]
        row = dict(
            id=_id("ep", f"{entity_key}:{etype}"),
            entity_id=ent["id"],
            endpoint_type=etype,
            url=f"https://fhir.{entity_key}.example.org/r4",
            connection_type="SMART on FHIR",
            name=f"{ent['name']} FHIR R4 Endpoint",
            description=f"Synthetic {etype} endpoint for {ent['name']}.",
            status="active",
            payload_type="application/fhir+json",
            environment="production",
            managing_org_id=ent["id"],
        )
        self.endpoints.append(row)
        return row

    # ---- standard identifier bundle per entity --------------------------------
    def issue_standard_identifiers(self, ent):
        key, level, etype = ent["key"], ent["entity_level"], ent["entity_type"]
        # Mandatory TEFCAID + HCID (TEFCAID primary).
        self.add_identifier(key, "tefcaid", self.next_tefcaid(), is_primary=True)
        self.add_identifier(key, "hcid", self.next_hcid())
        # NPI ~85%: skip for QHINs and vendor/clearinghouse (the IT/no-NPI ~15%).
        no_npi_type = etype in ("vendor", "clearinghouse")
        if level != "qhin" and not no_npi_type and self.rng.random() < 0.90:
            self.add_identifier(key, "npi", self.next_npi())
        # CCN ~20% (facility-ish types).
        if etype in ("hospital_system",) or self.rng.random() < 0.15:
            if level != "qhin":
                self.add_identifier(key, "ccn", self.next_ccn())
        # CLIA for laboratories (~5% overall).
        if etype == "laboratory":
            self.add_identifier(key, "clia", self.next_clia())
        # NAIC for health plans (~10% overall).
        if etype == "health_plan":
            self.add_identifier(key, "naic", self.next_naic())

    # ---- base dataset ---------------------------------------------------------
    def build_base(self):
        # QHINs
        for key, name, state, ddate, op, ver in QHINS:
            ent = self.add_entity(key, name, "qhin", "health_information_network", state,
                                  op_status=op, ver_status=ver,
                                  designation_date=ddate, onboarding_date=ddate,
                                  purposes=["treatment", "payment", "healthcare_operations",
                                            "public_health", "individual_access"])
            self.qhin_of[key] = key
            self.issue_standard_identifiers(ent)
            self.add_endpoint(key, "fhir_r4")

        # Participants — 45 across the 10 non-empty QHINs.
        part_counts = self._participant_counts()          # {qhin_key: n}, sums to 45
        part_status = self._status_cycle(35, 5, 3, 2)      # verified/in_review/not_verified/inactive
        p_idx = 0
        self.participants: list[str] = []
        for q_i, (qkey, *_rest) in enumerate(QHINS):
            n = part_counts.get(qkey, 0)
            for j in range(n):
                p_idx += 1
                pkey = f"part-{p_idx:03d}"
                etype = _PART_TYPES[(p_idx - 1) % len(_PART_TYPES)]
                state = _STATES[(p_idx - 1) % len(_STATES)]
                status = next(part_status)
                op = "inactive" if status == "inactive" else "active"
                is_active = status != "inactive"
                name = self._participant_name(etype, state, p_idx)
                ent = self.add_entity(pkey, name, "participant", etype, state,
                                      op_status=op, ver_status=status if status != "inactive" else "verified",
                                      onboarding_date=dt.date(2024, 1 + (p_idx % 12), 1 + (p_idx % 27)),
                                      is_active=is_active)
                self.qhin_of[pkey] = qkey
                self.children_of.setdefault(qkey, []).append(pkey)
                self.issue_standard_identifiers(ent)
                # belongs_to QHIN
                self.add_relationship(qkey, pkey, "belongs_to",
                                      ent["onboarding_date"] or dt.date(2024, 1, 1))
                # a subset of participants publish endpoints
                if p_idx % 4 == 0:
                    self.add_endpoint(pkey, "fhir_r4")
                self.participants.append(pkey)

        # Sub-Participants — 2-4 each, ~120 total.
        sub_status = self._status_cycle(90, 15, 10, 5)
        s_idx = 0
        self.subs: list[str] = []
        for p_i, pkey in enumerate(self.participants, start=1):
            # Deterministic 2/3 split summing to exactly 120 (15×2 + 30×3).
            n = 2 if (p_i % 3 == 0) else 3
            for j in range(n):
                s_idx += 1
                skey = f"sub-{s_idx:03d}"
                suffix, etype = _SUB_KINDS[(s_idx - 1) % len(_SUB_KINDS)]
                pstate = self.by_key[pkey]["state"]
                status = next(sub_status)
                op = "inactive" if status == "inactive" else "active"
                is_active = status != "inactive"
                name = f"{self.rng.choice(_ADJ)} {suffix}"
                ent = self.add_entity(skey, name, "sub_participant", etype, pstate,
                                      op_status=op, ver_status=status if status != "inactive" else "verified",
                                      onboarding_date=dt.date(2024, 6, 1) + dt.timedelta(days=s_idx % 300),
                                      is_active=is_active)
                self.qhin_of[skey] = self.qhin_of[pkey]
                self.children_of.setdefault(pkey, []).append(skey)
                self.issue_standard_identifiers(ent)
                self.add_relationship(pkey, skey, "sub_participant_of",
                                      ent["onboarding_date"] or dt.date(2024, 6, 1))
                self.subs.append(skey)

    def _participant_counts(self):
        counts = {}
        active_qhins = [q[0] for q in QHINS if q[0] != ZERO_PARTICIPANT_QHIN]
        # 45 over 10 QHINs: five 5s + five 4s = 45.
        plan = [5, 5, 5, 5, 5, 4, 4, 4, 4, 4]
        for qkey, c in zip(active_qhins, plan):
            counts[qkey] = c
        counts[ZERO_PARTICIPANT_QHIN] = 0
        return counts

    def _status_cycle(self, v, ir, nv, inact):
        """Yields statuses in a stable interleaved order matching the given counts."""
        seq = (["verified"] * v + ["in_review"] * ir +
               ["not_verified"] * nv + ["inactive"] * inact)
        # interleave deterministically for a realistic spread
        self.rng.shuffle(seq)
        return iter(seq)

    def _participant_name(self, etype, state, idx):
        base = f"{self.rng.choice(_ADJ)} {self.rng.choice(_NOUN)}"
        return {
            "hospital_system": f"{base} Health System",
            "health_plan": f"{base} Health Plan",
            "health_information_exchange": f"{base} Health Information Exchange",
            "provider": f"{base} Medical Group",
            "clearinghouse": f"{base} Data Clearinghouse",
            "vendor": f"{base} Health IT Solutions",
            "government_agency": f"{state} Department of Health ({base})",
            "laboratory": f"{base} Laboratories",
        }[etype]

    # ---- FHIR + versions (after mutations so snapshots reflect final state) ----
    def _identifiers_for(self, ent_id):
        return [i for i in self.identifiers if i["entity_id"] == ent_id]

    def _parent_reference(self, ent):
        """Return partOf reference key for a participant/sub, else None."""
        key = ent["key"]
        if ent["entity_level"] == "participant":
            return self.qhin_of.get(key)
        if ent["entity_level"] == "sub_participant":
            # its participant is the parent in children_of
            for pkey, kids in self.children_of.items():
                if key in kids and self.by_key[pkey]["entity_level"] == "participant":
                    return pkey
        if ent["entity_level"] == "child":
            for pkey, kids in self.children_of.items():
                if key in kids:
                    return pkey
        return None

    def build_fhir_and_versions(self):
        for ent in self.entities:
            idents = self._identifiers_for(ent["id"])
            fhir = {
                "resourceType": "Organization",
                "id": str(ent["id"]),
                "active": bool(ent["is_active"]),
                "name": ent["name"],
                "identifier": [
                    {"system": (i["system_uri"] or "urn:unknown"), "value": i["identifier_value"]}
                    for i in idents
                ],
                "type": [{
                    "coding": [{
                        "system": "urn:docuaction:tefca/fhir/CodeSystem/entity-type",
                        "code": ent["entity_type"],
                    }]
                }],
                "address": [{
                    "line": [ent["address"]],
                    "city": ent["city"],
                    "state": ent["state"],
                    "postalCode": ent["zip"],
                    "country": "US",
                }],
            }
            if ent["entity_level"] == "qhin":
                fhir["meta"] = {"profile": [QHIN_PROFILE]}
            parent_key = self._parent_reference(ent)
            if parent_key:
                fhir["partOf"] = {"reference": f"Organization/{self.by_key[parent_key]['id']}"}
            ent["fhir_resource"] = fhir

            # initial version snapshot
            snap = {k: (v.isoformat() if isinstance(v, dt.date) else v)
                    for k, v in ent.items()
                    if k not in ("key", "id", "fhir_resource")}
            snap["fhir_resource"] = fhir
            self.versions.append(dict(
                id=_id("ver", f"{ent['key']}:1"),
                entity_id=ent["id"],
                version_number=1,
                snapshot_data=snap,
                change_reason="initial_import",
                changed_by=None,
                change_summary="Initial import snapshot (Phase 1C seed).",
            ))

    # ---- special (non-defect) scenarios: dual / historical / merger -----------
    def build_special_scenarios(self):
        # 3 entities with dual QHIN affiliations (affiliated_with a 2nd QHIN).
        for n, pkey in enumerate(self.participants[23:26], start=1):
            home_q = self.qhin_of[pkey]
            other_q = next(q[0] for q in QHINS
                           if q[0] not in (home_q, ZERO_PARTICIPANT_QHIN))
            self.add_relationship(other_q, pkey, "affiliated_with",
                                  dt.date(2024, 3, 1), tag=f"dual{n}",
                                  notes="Dual QHIN affiliation (special scenario).")
        # 2 entities with historical QHIN changes (old belongs_to end-dated + new).
        for n, pkey in enumerate(self.participants[26:28], start=1):
            old_q = self.qhin_of[pkey]
            new_q = next(q[0] for q in QHINS
                         if q[0] not in (old_q, ZERO_PARTICIPANT_QHIN))
            # end-date the existing belongs_to
            for rel in self.relationships:
                if (rel["child_entity_id"] == self.by_key[pkey]["id"]
                        and rel["relationship_type"] == "belongs_to"
                        and rel["status"] == "active"):
                    rel["status"] = "historical"
                    rel["end_date"] = dt.date(2025, 6, 30)
                    rel["notes"] = "Historical QHIN affiliation (migrated)."
                    break
            self.add_relationship(new_q, pkey, "belongs_to", dt.date(2025, 7, 1),
                                  tag=f"hist{n}", notes="Current QHIN after migration.")
            self.qhin_of[pkey] = new_q
        # 1 merger: participant merged_into another participant (same QHIN).
        a, b = self.participants[28], self.participants[29]
        self.add_relationship(b, a, "merged_into", dt.date(2025, 2, 1),
                              notes="Entity A merged into Entity B (special scenario).")
        self.by_key[a]["operational_status"] = "inactive"

    # ---- Phase 1D: 36 intentional defects -------------------------------------
    def _mark(self, key, def_id):
        ent = self.by_key[key]
        ent["exchange_purposes"].setdefault("defects", []).append(def_id)

    def _record(self, def_id, category, title, expected, entities, detail):
        self.defects.append(dict(
            id=def_id, category=category, title=title,
            expected_detection=expected,
            entities=[{"key": k, "id": str(self.by_key[k]["id"]), "name": self.by_key[k]["name"]}
                      for k in entities],
            detail=detail,
        ))
        for k in entities:
            self._mark(k, def_id)

    def _find_ident(self, key, itype):
        eid = self.by_key[key]["id"]
        return next((i for i in self.identifiers
                     if i["entity_id"] == eid and i["identifier_type"] == itype), None)

    def _remove_ident(self, key, itype):
        row = self._find_ident(key, itype)
        if row:
            self.identifiers.remove(row)
        return row

    def build_defects(self):
        P, S = self.participants, self.subs

        # ═══ IDENTITY (12) ═══
        # DEF-ID-001 Duplicate NPI (shared 1234599001)
        dup_npi = _npi("123459900")  # -> 1234599001
        self._remove_ident(P[0], "npi"); self._remove_ident(P[1], "npi")
        self.add_identifier(P[0], "npi", dup_npi, tag="dup001a")
        self.add_identifier(P[1], "npi", dup_npi, system_uri=None, tag="dup001b")  # NULL uri to coexist
        self._record("DEF-ID-001", "identity", "Duplicate NPI",
                     "npi_duplicate — two active entities share the same NPI.",
                     [P[0], P[1]], f"Both entities carry NPI {dup_npi} (second row has NULL system_uri to bypass the unique index).")

        # DEF-ID-002 Duplicate HCID
        h = self._find_ident(P[2], "hcid")["identifier_value"]
        self._remove_ident(P[3], "hcid")
        self.add_identifier(P[3], "hcid", h, system_uri=None, tag="dup002")
        self._record("DEF-ID-002", "identity", "Duplicate HCID",
                     "hcid_duplicate — HCID reused across two entities.",
                     [P[2], P[3]], f"HCID {h} shared by both entities.")

        # DEF-ID-003 Missing NPI on treatment entity
        self._remove_ident(S[0], "npi")
        self.by_key[S[0]]["exchange_purposes"]["purposes"] = ["treatment"]
        self._record("DEF-ID-003", "identity", "Missing NPI on treatment entity",
                     "identifier_missing — treatment provider has no NPI.",
                     [S[0]], "Treatment-purpose provider with no NPI identifier.")

        # DEF-ID-004 Invalid NPI checksum (fails Luhn)
        self._remove_ident(P[4], "npi")
        bad = _npi("123450004", valid=False)
        self.add_identifier(P[4], "npi", bad, tag="bad004")
        self._record("DEF-ID-004", "identity", "Invalid NPI checksum",
                     "npi_invalid — NPI fails the Luhn check.",
                     [P[4]], f"NPI {bad} has an invalid check digit.")

        # DEF-ID-005 Retired TEFCAID on active entity
        t = self._find_ident(P[5], "tefcaid")
        t["identifier_status"] = "retired"; t["end_date"] = dt.date(2025, 1, 1)
        self._record("DEF-ID-005", "identity", "Retired TEFCAID on active entity",
                     "identifier_retired — active entity's TEFCAID is retired.",
                     [P[5]], "Entity is active but its (mandatory) TEFCAID is marked retired.")

        # DEF-ID-006 Missing TEFCAID (mandatory)
        self._remove_ident(P[6], "tefcaid")
        self._record("DEF-ID-006", "identity", "Missing TEFCAID",
                     "identifier_missing — mandatory TEFCAID absent.",
                     [P[6]], "Mandatory TEFCAID removed.")

        # DEF-ID-007 Missing HCID (mandatory)
        self._remove_ident(P[7], "hcid")
        self._record("DEF-ID-007", "identity", "Missing HCID",
                     "identifier_missing — mandatory HCID absent.",
                     [P[7]], "Mandatory HCID removed.")

        # DEF-ID-008 NPI not in NPPES
        self._remove_ident(P[8], "npi")
        npi8 = _npi("123450808")
        self.add_identifier(P[8], "npi", npi8, tag="notfound008")
        self._record("DEF-ID-008", "identity", "NPI not in NPPES",
                     "npi_invalid / not_found — NPI absent from NPPES.",
                     [P[8]], f"Synthetic NPI {npi8} that will not resolve in NPPES.")

        # DEF-ID-009 NPI type mismatch (Type 1 individual NPI on an organization)
        self._remove_ident(P[9], "npi")
        npi9 = _npi("123450909")
        self.add_identifier(P[9], "npi", npi9, tag="type1_009")
        self._record("DEF-ID-009", "identity", "NPI type mismatch (Type 1 on org)",
                     "enrollment_mismatch — Type-1 (individual) NPI on an organization.",
                     [P[9]], f"Organization entity carries individual (Type 1) NPI {npi9}.")

        # DEF-ID-010 Expired CCN
        self._remove_ident(P[10], "ccn")
        ccn10 = self.next_ccn()
        self.add_identifier(P[10], "ccn", ccn10, status="expired",
                            end=dt.date(2024, 12, 31), tag="expired010")
        self._record("DEF-ID-010", "identity", "Expired CCN",
                     "enrollment_expired — CCN past its end date.",
                     [P[10]], f"CCN {ccn10} marked expired (ended 2024-12-31).")

        # DEF-ID-011 Duplicate TEFCAID across QHINs (P[11] & P[12] under different QHINs)
        # ensure the two are under different QHINs
        p11, p12 = P[11], P[12]
        t11 = self._find_ident(p11, "tefcaid")["identifier_value"]
        self._remove_ident(p12, "tefcaid")
        self.add_identifier(p12, "tefcaid", t11, system_uri=None, tag="dup011", is_primary=True)
        self._record("DEF-ID-011", "identity", "Duplicate TEFCAID across QHINs",
                     "identifier_conflict — same TEFCAID under two QHINs.",
                     [p11, p12], f"TEFCAID {t11} appears under QHINs "
                                 f"{self.qhin_of[p11]} and {self.qhin_of[p12]}.")

        # DEF-ID-012 Multiple active NPIs on one entity
        npi_a = self.next_npi(); npi_b = self.next_npi()
        self._remove_ident(P[13], "npi")
        self.add_identifier(P[13], "npi", npi_a, tag="multi012a")
        self.add_identifier(P[13], "npi", npi_b, tag="multi012b")
        self._record("DEF-ID-012", "identity", "Multiple active NPIs on one entity",
                     "identifier_conflict — >1 active NPI on a single entity.",
                     [P[13]], f"Entity carries two active NPIs ({npi_a}, {npi_b}).")

        # ═══ HIERARCHY (12) ═══
        # DEF-HR-001 Orphan Sub-Participant (parent edge inactive, no active parent)
        self._deactivate_child_edge(S[1])
        self._record("DEF-HR-001", "hierarchy", "Orphan Sub-Participant",
                     "orphan_entity — sub-participant with no active parent.",
                     [S[1]], "Only sub_participant_of edge set to status=inactive.")

        # DEF-HR-002 Circular relationship (A->B->A)
        a, b = P[14], P[15]
        self.add_relationship(a, b, "contracts_with", dt.date(2024, 4, 1),
                              tag="circ_ab", notes="DEF-HR-002 circular edge A->B.")
        self.add_relationship(b, a, "contracts_with", dt.date(2024, 4, 2),
                              tag="circ_ba", notes="DEF-HR-002 circular edge B->A.")
        self._record("DEF-HR-002", "hierarchy", "Circular relationship (A→B→A)",
                     "circular_relationship — mutual parent edges.",
                     [a, b], "Two active contracts_with edges form a cycle.")

        # DEF-HR-003 Inactive parent with active children (op_status inactive, still is_active)
        par = P[16]
        self.by_key[par]["operational_status"] = "inactive"
        self._record("DEF-HR-003", "hierarchy", "Inactive parent with active children",
                     "inactive_parent — parent operational_status=inactive, children active.",
                     [par], "Parent operational_status=inactive; child sub_participant_of edges remain active.")

        # DEF-HR-004 Sub-Participant directly under QHIN
        s = S[2]
        self._deactivate_child_edge(s)
        qkey = self.qhin_of[s]
        self.add_relationship(qkey, s, "sub_participant_of", dt.date(2024, 5, 1),
                              tag="under_qhin004", notes="DEF-HR-004 sub directly under QHIN.")
        self._record("DEF-HR-004", "hierarchy", "Sub-Participant directly under QHIN",
                     "broken_hierarchy — sub_participant_of points at a QHIN.",
                     [s, qkey], "Sub-participant's active parent is a QHIN, not a Participant.")

        # DEF-HR-005 Merged entity with orphaned children
        merged = P[17]
        target = P[18]
        self.add_relationship(target, merged, "merged_into", dt.date(2025, 3, 1),
                              tag="merge005", notes="DEF-HR-005 merged; children left orphaned.")
        self.by_key[merged]["operational_status"] = "inactive"
        self.by_key[merged]["is_active"] = False
        self._record("DEF-HR-005", "hierarchy", "Merged entity with orphaned children",
                     "orphan_entity — children still point to a merged/inactive parent.",
                     [merged, target], "Parent merged_into target and deactivated; its sub_participant_of children remain.")

        # DEF-HR-006 QHIN with zero Participants
        self._record("DEF-HR-006", "hierarchy", "QHIN with zero Participants",
                     "broken_hierarchy — QHIN has no participants.",
                     [ZERO_PARTICIPANT_QHIN], "Oracle Health QHIN intentionally has no Participant relationships.")

        # DEF-HR-007 Participant under another Participant
        child_p, parent_p = P[19], P[20]
        self.add_relationship(parent_p, child_p, "belongs_to", dt.date(2024, 6, 15),
                              tag="p_under_p007", notes="DEF-HR-007 participant under participant.")
        self._record("DEF-HR-007", "hierarchy", "Participant under another Participant",
                     "broken_hierarchy — belongs_to targets a Participant.",
                     [child_p, parent_p], "A Participant belongs_to another Participant instead of a QHIN.")

        # DEF-HR-008 Only historical relationships (expired)
        s8 = S[3]
        self._historicize_child_edge(s8)
        self._record("DEF-HR-008", "hierarchy", "Only historical relationships",
                     "orphan_entity — entity has only historical (ended) relationships.",
                     [s8], "Sole sub_participant_of edge is status=historical with a past end_date.")

        # DEF-HR-009 Two active parent relationships
        s9 = S[4]
        other_parent = P[21] if P[21] != self._parent_key(s9) else P[22]
        self.add_relationship(other_parent, s9, "sub_participant_of", dt.date(2024, 7, 1),
                              tag="twoparent009", notes="DEF-HR-009 second active parent.")
        self._record("DEF-HR-009", "hierarchy", "Two active parent relationships",
                     "broken_hierarchy — two active sub_participant_of parents.",
                     [s9], "Sub-participant has two concurrent active parent edges.")

        # DEF-HR-010 Entity with zero relationships (strip a participant's edges + subs)
        z = P[30]
        self._strip_all_edges(z)
        self._record("DEF-HR-010", "hierarchy", "Entity with zero relationships",
                     "orphan_entity — participant has no relationships at all.",
                     [z], "All belongs_to / child edges removed.")

        # DEF-HR-011 4-level deep Sub-Sub-Participant (adds a 'child' entity)
        base_sub = S[5]
        ckey = "child-001"
        pstate = self.by_key[base_sub]["state"]
        child = self.add_entity(ckey, f"{self.rng.choice(_ADJ)} Satellite Clinic",
                                "child", "provider", pstate,
                                onboarding_date=dt.date(2025, 1, 15))
        self.qhin_of[ckey] = self.qhin_of[base_sub]
        self.children_of.setdefault(base_sub, []).append(ckey)
        self.issue_standard_identifiers(child)
        self.add_relationship(base_sub, ckey, "sub_participant_of", dt.date(2025, 1, 15),
                              tag="deep011", notes="DEF-HR-011 4th-level entity.")
        self._record("DEF-HR-011", "hierarchy", "4-level deep Sub-Sub-Participant",
                     "broken_hierarchy — hierarchy exceeds QHIN>Participant>Sub depth.",
                     [ckey, base_sub], "A 'child' entity sits under a Sub-Participant (4th level).")

        # DEF-HR-012 Soft-deleted parent (is_active=false) with active children
        sd = P[31]
        self.by_key[sd]["is_active"] = False
        self._record("DEF-HR-012", "hierarchy", "Soft-deleted parent",
                     "inactive_parent — parent is_active=false, children active.",
                     [sd], "Parent is soft-deleted (is_active=false) but child edges remain active.")

        # ═══ VERIFICATION (12) ═══ (latent; discovery is a later phase)
        vr = [
            ("DEF-VR-001", "OIG LEIE exclusion", "exclusion_leie",
             "Entity's NPI/name matches a (synthetic) OIG LEIE excluded record."),
            ("DEF-VR-002", "SAM.gov debarment", "exclusion_sam",
             "Entity matches a (synthetic) SAM.gov exclusion/debarment record."),
            ("DEF-VR-003", "PECOS enrollment mismatch", "enrollment_mismatch",
             "Entity's enrollment details disagree with PECOS."),
            ("DEF-VR-004", "Address mismatch vs NPPES", "address_mismatch",
             "Entity street address differs from the NPPES record."),
            ("DEF-VR-005", "Name mismatch vs NPPES", "name_mismatch",
             "Entity legal name differs from the NPPES record."),
            ("DEF-VR-006", "ZIP mismatch (transposed)", "zip_mismatch",
             "Entity ZIP has two transposed digits vs NPPES."),
            ("DEF-VR-007", "State mismatch", "state_mismatch",
             "Entity state differs from the NPPES record."),
            ("DEF-VR-008", "NPI not found in NPPES", "npi_invalid",
             "Entity NPI does not resolve in NPPES."),
            ("DEF-VR-009", "PECOS enrollment expired", "enrollment_expired",
             "Entity's PECOS enrollment period has lapsed."),
            ("DEF-VR-010", "Entity type mismatch", "enrollment_mismatch",
             "Entity type disagrees with NPPES taxonomy classification."),
            ("DEF-VR-011", "Missing taxonomy code", "identifier_missing",
             "Entity has no provider taxonomy code."),
            ("DEF-VR-012", "Multiple NPPES records for same NPI", "npi_duplicate",
             "The entity's NPI maps to multiple NPPES records."),
        ]
        for n, (did, title, ftype, detail) in enumerate(vr):
            skey = S[6 + n]
            # Represent locally-materializable conditions where possible.
            if did == "DEF-VR-006":
                z = self.by_key[skey]["zip"]
                self.by_key[skey]["zip"] = (z[1] + z[0] + z[2:]) if len(z) >= 2 else z
            if did == "DEF-VR-007":
                self.by_key[skey]["state"] = "ZZ"
            if did == "DEF-VR-005":
                self.by_key[skey]["display_name"] = self.by_key[skey]["name"] + " (dba variant)"
            if did in ("DEF-VR-001", "DEF-VR-002", "DEF-VR-003", "DEF-VR-008", "DEF-VR-009"):
                self.by_key[skey]["verification_status"] = "exception"
            self._record(did, "verification", title,
                         f"{ftype} — {detail}", [skey], detail)

    # ---- edge helpers used by defects ----------------------------------------
    def _child_edges(self, key):
        eid = self.by_key[key]["id"]
        return [r_ for r_ in self.relationships
                if r_["child_entity_id"] == eid
                and r_["relationship_type"] in ("belongs_to", "sub_participant_of")]

    def _parent_key(self, key):
        """Return the participant key that owns this sub (from children_of)."""
        for pkey, kids in self.children_of.items():
            if key in kids:
                return pkey
        return None

    def _deactivate_child_edge(self, key):
        for e in self._child_edges(key):
            if e["status"] == "active":
                e["status"] = "inactive"
                e["end_date"] = dt.date(2025, 6, 1)

    def _historicize_child_edge(self, key):
        for e in self._child_edges(key):
            if e["status"] == "active":
                e["status"] = "historical"
                e["end_date"] = dt.date(2024, 12, 31)

    def _strip_all_edges(self, key):
        eid = self.by_key[key]["id"]
        self.relationships = [
            r_ for r_ in self.relationships
            if r_["child_entity_id"] != eid and r_["parent_entity_id"] != eid
        ]

    # ---- orchestration --------------------------------------------------------
    def generate(self):
        self.build_base()
        self.build_special_scenarios()
        self.build_defects()
        # extra downstream_of edges to reflect QHIN->sub reachability (and clear ~180 floor)
        for skey in self.subs[:15]:
            self.add_relationship(self.qhin_of[skey], skey, "downstream_of",
                                  dt.date(2024, 8, 1), tag="downstream",
                                  notes="Downstream reachability edge.")
        self.build_fhir_and_versions()
        return self


# ══════════════════════════════════════════════════════════════════════════════
# Persistence
# ══════════════════════════════════════════════════════════════════════════════

async def _upsert(session, model, rows):
    """Multi-row upsert on PK id (deterministic ids => idempotent)."""
    if not rows:
        return
    # strip generator-only keys
    clean = [{k: v for k, v in row.items() if k != "key"} for row in rows]
    table = model.__table__
    # chunk to keep parameter counts reasonable
    CH = 200
    for i in range(0, len(clean), CH):
        batch = clean[i:i + CH]
        stmt = pg_insert(table).values(batch)
        update = {c.name: getattr(stmt.excluded, c.name)
                  for c in table.columns if c.name not in ("id", "created_at")}
        stmt = stmt.on_conflict_do_update(index_elements=["id"], set_=update)
        await session.execute(stmt)


async def _ensure_tables():
    tables = [Base.metadata.tables[t] for t in r.TEFCA_REG_TABLE_ORDER]
    async with engine.begin() as conn:
        await conn.run_sync(lambda c: Base.metadata.create_all(c, tables=tables, checkfirst=True))


async def seed_all(session, gen: _Gen):
    # entities first (FK parent), then dependents.
    await _upsert(session, r.TefcaRegEntity, gen.entities)
    await _upsert(session, r.TefcaEntityIdentifier, gen.identifiers)
    await _upsert(session, r.TefcaEntityRelationship, gen.relationships)
    await _upsert(session, r.TefcaEntityVersion, gen.versions)
    await _upsert(session, r.TefcaEntityEndpoint, gen.endpoints)
    logger.info("seeded entities=%d identifiers=%d relationships=%d versions=%d endpoints=%d",
                len(gen.entities), len(gen.identifiers), len(gen.relationships),
                len(gen.versions), len(gen.endpoints))


async def validate(session):
    counts = {}
    for table in EXPECTED:
        counts[table] = int(await session.scalar(
            select(func.count()).select_from(Base.metadata.tables[table])) or 0)
    return counts


# ══════════════════════════════════════════════════════════════════════════════
# Defect scenarios documentation
# ══════════════════════════════════════════════════════════════════════════════

def _defect_doc_path():
    # repo root = .../backend ; write under docs/tefca/
    here = os.path.dirname(os.path.abspath(__file__))       # .../app/tefca_registry
    root = os.path.dirname(os.path.dirname(here))           # .../backend
    return os.path.join(root, "docs", "TEFCA_DEFECT_SCENARIOS.md")


def render_defect_doc(gen: _Gen) -> str:
    lines = []
    lines.append("# TEFCA Registry — Intentional Defect Scenarios (Phase 1D)")
    lines.append("")
    lines.append("This dataset embeds **36 intentional defects** across the ~176 seeded TEFCA "
                 "registry entities. They are **latent data problems** — no verification jobs, "
                 "checks, or findings are created by the seed (those remain at 0). Discovery is a "
                 "later phase; this document is the ground-truth answer key.")
    lines.append("")
    lines.append("All identifiers are **synthetic** (NPIs in the fake `1234xxxxx` block). "
                 "Affected entities also carry a `defects` marker inside their "
                 "`exchange_purposes` JSONB, and relationship-level defects are tagged in the "
                 "relationship `notes`.")
    lines.append("")
    by_cat = {"identity": [], "hierarchy": [], "verification": []}
    for d in gen.defects:
        by_cat[d["category"]].append(d)
    titles = {"identity": "Identity Defects (12)",
              "hierarchy": "Hierarchy Defects (12)",
              "verification": "Verification Defects (12)"}
    for cat in ("identity", "hierarchy", "verification"):
        lines.append(f"## {titles[cat]}")
        lines.append("")
        lines.append("| ID | Title | Expected detection | Affected entities |")
        lines.append("|----|-------|--------------------|-------------------|")
        for d in by_cat[cat]:
            ents = "; ".join(f"{e['name']} (`{e['id'][:8]}`)" for e in d["entities"])
            lines.append(f"| {d['id']} | {d['title']} | {d['expected_detection']} | {ents} |")
        lines.append("")
        for d in by_cat[cat]:
            lines.append(f"### {d['id']} — {d['title']}")
            lines.append(f"- **Category:** {d['category']}")
            lines.append(f"- **How it is seeded:** {d['detail']}")
            lines.append(f"- **Expected detection:** {d['expected_detection']}")
            lines.append("- **Affected entities:**")
            for e in d["entities"]:
                lines.append(f"  - `{e['id']}` — {e['name']} (key `{e['key']}`)")
            lines.append("")
    return "\n".join(lines) + "\n"


def write_defect_doc(gen: _Gen) -> str:
    path = _defect_doc_path()
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(render_defect_doc(gen))
    return path


# ══════════════════════════════════════════════════════════════════════════════
# Entry point
# ══════════════════════════════════════════════════════════════════════════════

async def run():
    gen = _Gen().generate()
    await _ensure_tables()
    async with async_session_maker() as session:
        await seed_all(session, gen)
        await session.commit()
        counts = await validate(session)
    doc_path = write_defect_doc(gen)
    return gen, counts, doc_path


def _print_report(gen, counts, doc_path):
    print("\nTEFCA registry seed — record counts")
    print("=" * 60)
    print(f"{'table':<32}{'count':>8}{'target':>10}  ok")
    print("-" * 60)
    all_ok = True
    for table, expected in EXPECTED.items():
        actual = counts.get(table, 0)
        if table in _FLOOR:
            ok = actual >= expected
            tgt = f">={expected}"
        elif table in _TOLERANCE:
            ok = abs(actual - expected) <= _TOLERANCE[table]
            tgt = f"~{expected}"
        else:
            ok = actual == expected
            tgt = str(expected)
        all_ok &= ok
        print(f"{table:<32}{actual:>8}{tgt:>10}  {'OK' if ok else 'CHECK'}")
    print("=" * 60)
    print(f"defects embedded: {len(gen.defects)} (expected 36)")
    print(f"defect doc: {doc_path}")
    print("RESULT:", "ALL COUNTS WITHIN TARGET" if all_ok and len(gen.defects) == 36
          else "REVIEW NEEDED")
    return all_ok and len(gen.defects) == 36


def main():
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
    gen, counts, doc_path = asyncio.run(run())
    ok = _print_report(gen, counts, doc_path)
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
