"""Output validation and evidence-quality scoring for TEFCA entity resolution.

Every AI output is validated here. Output that fails NEVER enters the
verification pipeline — the orchestrator returns text only when validation
passed, so a malformed or out-of-role response cannot reach a reviewer dressed
as evidence.

THE CENTRAL DISTINCTION IN THIS FILE:

    ai_raw_confidence      — the model's opinion of its own answer.
                             LOGGED. Never used for any decision.
    evidence_quality_score — computed from objective signals that exist
                             independently of the model (NPI equality, USPS
                             normalization, string similarity, source
                             agreement). Used for triage and reporting.

A model's self-reported confidence is a fluent number, not a measurement: it is
generated by the same process that generated the answer, and it is high exactly
when the model is confidently wrong. Basing anything on it would let the system
under audit grade its own paper. Objective signals cannot do that, which is why
they and only they carry weight.
"""
from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

from app.tefca_registry.ai.policy_engine import TEFCAPolicyEngine

logger = logging.getLogger("docuaction.tefca.ai.validation")

REQUIRED_FIELDS = ("match", "confidence", "rationale")

# Phrases asserting certainty the model is not entitled to hold. It compares two
# directory records; it cannot know that two organizations are the same legal
# entity. The point is not word policing — it is that a rationale reading "I can
# confirm this is the same entity" changes how a reviewer weighs it, and an
# advisory system must not be able to manufacture that weight.
BANNED_ASSERTIONS = (
    "this is definitely",
    "i can confirm",
    "there is no doubt",
    "this entity is clearly",
    "i am certain",
)

MAX_RATIONALE_CHARS = 2000


@dataclass
class ValidationResult:
    passed: bool
    errors: List[str] = field(default_factory=list)
    data: Optional[Dict[str, Any]] = None

    @property
    def ai_raw_confidence(self) -> Optional[float]:
        """The model's self-reported confidence, for the audit row ONLY.

        Named to make misuse obvious at the call site: `ai_raw_confidence` does
        not read like something safe to threshold on.
        """
        if not self.data:
            return None
        value = self.data.get("confidence")
        return float(value) if isinstance(value, (int, float)) and not isinstance(value, bool) \
            else None


class TEFCAEvidenceQualityEngine:
    """Decision quality from OBJECTIVE evidence — never from the model.

    Weights come from YAML so calibration is a policy change rather than a
    deployment. They are currently uncalibrated placeholders
    (CALIBRATION_REQUIRED); until ONC approves real weights the score is
    recorded and displayed but gates nothing, which is why shipping it
    uncalibrated is safe.
    """

    def __init__(self, policy: Optional[TEFCAPolicyEngine] = None):
        self.policy = policy or TEFCAPolicyEngine()
        self.weights: Dict[str, float] = self.policy.get_weights()

    @property
    def is_calibrated(self) -> bool:
        return self.policy.is_calibrated()

    def calculate_score(self, evidence: Optional[Dict[str, Any]]) -> float:
        """Sum the weights of the signals that fired, capped at 1.0.

        Returns 0.0 for absent evidence and for an unloaded policy (no weights
        means nothing can score), which reads correctly downstream: no evidence
        is no support for a match, and both cases still require review.
        """
        if not evidence or not self.weights:
            return 0.0

        score = 0.0
        if evidence.get("npi_exact_match"):
            score += self.weights.get("npi_exact_match", 0.0)
        if evidence.get("address_normalized_match"):
            score += self.weights.get("address_normalized_match", 0.0)
        if evidence.get("usps_zip4_match"):
            score += self.weights.get("usps_zip4_match", 0.0)
        if _as_float(evidence.get("name_similarity")) > 0.85:
            score += self.weights.get("name_similarity_above_085", 0.0)
        if evidence.get("entity_type_match"):
            score += self.weights.get("entity_type_match", 0.0)
        if evidence.get("source_agreement"):
            score += self.weights.get("source_agreement", 0.0)
        if evidence.get("no_conflicting_fields"):
            score += self.weights.get("no_conflicting_fields", 0.0)
        if evidence.get("models_agree"):
            score += self.weights.get("models_agree", 0.0)

        return round(min(score, 1.0), 4)

    def signals_fired(self, evidence: Optional[Dict[str, Any]]) -> List[str]:
        """Which signals contributed. Stored beside the score so an auditor can
        reconstruct the arithmetic rather than trusting the total."""
        if not evidence:
            return []
        fired = [k for k in ("npi_exact_match", "address_normalized_match",
                             "usps_zip4_match", "entity_type_match",
                             "source_agreement", "no_conflicting_fields",
                             "models_agree") if evidence.get(k)]
        if _as_float(evidence.get("name_similarity")) > 0.85:
            fired.append("name_similarity_above_085")
        return fired


class TEFCAValidationEngine:
    """Validates every AI output before it is allowed near the pipeline."""

    def __init__(self, policy: Optional[TEFCAPolicyEngine] = None):
        self.policy = policy or TEFCAPolicyEngine()

    def validate_entity_match(self, ai_output: Optional[str],
                              context: Optional[Dict[str, Any]] = None) -> ValidationResult:
        """Structure, range, role, and egress checks.

        All checks run and all failures are collected rather than returning on
        the first. A reviewer investigating a rejection wants the full list; two
        round trips to discover two problems is a worse artifact.
        """
        context = context or {}
        errors: List[str] = []

        if not ai_output or not str(ai_output).strip():
            return ValidationResult(False, ["Empty response"])

        try:
            data = json.loads(ai_output)
        except (json.JSONDecodeError, TypeError):
            # No brace-scraping salvage. The prompt requires JSON only; text
            # around the JSON means the model stepped outside its instructions,
            # and quietly repairing that hides exactly the drift this engine
            # exists to detect.
            return ValidationResult(False, ["Invalid JSON"])

        if not isinstance(data, dict):
            return ValidationResult(False, ["Response is not a JSON object"])

        for field_name in REQUIRED_FIELDS:
            if field_name not in data:
                errors.append(f"Missing: {field_name}")

        if "confidence" in data:
            confidence = data["confidence"]
            if isinstance(confidence, bool) or not isinstance(confidence, (int, float)):
                errors.append(f"Confidence {confidence!r} is not a number")
            elif not (0.0 <= float(confidence) <= 1.0):
                errors.append(f"Confidence {confidence} outside [0,1]")

        # match is a three-state field: true / false / null (undetermined).
        # Anything else means the model invented a vocabulary.
        if "match" in data and data["match"] not in (True, False, None):
            errors.append(f"Match {data['match']!r} is not true, false, or null")

        rationale = data.get("rationale")
        if "rationale" in data:
            if not isinstance(rationale, str):
                errors.append("Rationale is not a string")
            else:
                lowered = rationale.lower()
                for assertion in BANNED_ASSERTIONS:
                    if assertion in lowered:
                        errors.append(f"Prohibited assertion: '{assertion}'")
                if len(rationale) > MAX_RATIONALE_CHARS:
                    errors.append(
                        f"Rationale exceeds {MAX_RATIONALE_CHARS} characters "
                        f"({len(rationale)})")

        errors.extend(self.check_egress(context))

        return ValidationResult(passed=not errors, errors=errors, data=data)

    def check_egress(self, context: Optional[Dict[str, Any]]) -> List[str]:
        """Re-verify that only allowlisted fields were sent.

        The orchestrator already filters to public fields before building the
        payload. This is the independent second check: the filter and the
        verification are separate code paths, so a bug in the filter is caught
        rather than confirmed. A PHI leak is not a defect worth trusting one
        implementation with.
        """
        context = context or {}
        sent = context.get("fields_sent")
        if not sent:
            return []

        allowed = set(self.policy.get_public_fields())
        if not allowed:
            # Unloaded policy: no field is authorized. Fail closed rather than
            # treating an empty allowlist as "no restrictions".
            return ["Unauthorized fields sent: policy unavailable, no field is approved"]

        unauthorized = set(sent) - allowed
        if unauthorized:
            return [f"Unauthorized fields sent: {sorted(unauthorized)}"]
        return []


def _as_float(value: Any) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return 0.0
