"""
FCC Bulletin — extended feed list (ADD-only companion to engine.py).
Auto-extracted from the client's fcc_daily_news.py FEEDS list, split into
ungated FCC.gov official feeds and gated outlet feeds. URLs deduplicated.
"""

# Ungated — FCC.gov official feeds (always on-topic). Format: (url, name)
EXTENDED_FCC_OFFICIAL = [
    ('https://www.fcc.gov/rss/news-releases', 'FCC.gov - News Releases'),
    ('https://www.fcc.gov/rss/headlines', 'FCC.gov - Headlines'),
    ('https://www.fcc.gov/rss/releases', 'FCC - All Recent Releases'),
    ('https://www.fcc.gov/rss/commissioner-statements', 'FCC - Commissioner Statements'),
    ('https://www.fcc.gov/rss/speeches', 'FCC - Commissioner Speeches'),
    ('https://www.fcc.gov/rss/orders', 'FCC - Orders'),
    ('https://www.fcc.gov/rss/public-notices', 'FCC - Public Notices'),
    ('https://www.fcc.gov/rss/nprm', 'FCC - Notices of Proposed Rules'),
    ('https://www.fcc.gov/rss/reports', 'FCC - Reports'),
    ('https://www.fcc.gov/rss/enforcement-bureau', 'FCC - Enforcement Bureau'),
    ('https://www.fcc.gov/rss/media-bureau', 'FCC - Media Bureau'),
    ('https://www.fcc.gov/rss/wireless-telecommunications-bureau', 'FCC - Wireless Bureau'),
    ('https://www.fcc.gov/rss/wireline-competition-bureau', 'FCC - Wireline Bureau'),
    ('https://www.fcc.gov/rss/consumer-governmental-affairs-bureau', 'FCC - Consumer Affairs Bureau'),
    ('https://www.fcc.gov/rss/space-bureau', 'FCC - Space Bureau'),
    ('https://www.fcc.gov/rss/public-safety-homeland-security-bureau', 'FCC - Public Safety Bureau'),
    ('https://www.fcc.gov/rss/office-engineering-technology', 'FCC - Office of Engineering'),
    ('https://www.fcc.gov/rss/office-economics-analytics', 'FCC - Office of Economics'),
    ('https://www.fcc.gov/rss/office-general-counsel', 'FCC - General Counsel'),
    ('https://www.fcc.gov/rss/office-inspector-general', 'FCC - Inspector General'),
    ('https://www.fcc.gov/rss/broadcast-actions', 'FCC - Broadcast Actions'),
    ('https://www.fcc.gov/rss/broadcast-applications', 'FCC - Broadcast Applications'),
    ('https://www.fcc.gov/rss/notices-apparent-liability', 'FCC - Notices of Liability'),
    ('https://www.fcc.gov/rss/fact-sheets', 'FCC - Fact Sheets'),
    ('https://www.fcc.gov/rss/court-filings', 'FCC - Court Filings'),
    ('https://www.fcc.gov/rss/international-bureau', 'FCC - International Bureau'),
]

# Gated — everything else; runs through the FCC relevance filter.
# Format: (url, name, paywalled=False)
EXTENDED_OUTLET_FEEDS = [
    ('https://www.federalregister.gov/documents/search.rss?conditions%5Bagencies%5D%5B%5D=federal-communications-commission', 'Federal Register - FCC', False),
    ('https://broadbandbreakfast.com/feed/', 'Broadband Breakfast', False),
    ('https://www.lightreading.com/rss.xml', 'Light Reading', False),
    ('https://www.fierce-network.com/rss/xml', 'Fierce Network', False),
    ('https://www.fiercewireless.com/rss/xml', 'Fierce Wireless', False),
    ('https://www.rcrwireless.com/feed', 'RCR Wireless', False),
    ('https://trdaily.com/feed/', 'TR Daily', False),
    ('https://www.telecompaper.com/rss/news', 'Telecompaper', False),
    ('https://www.totaltele.com/rss.xml', 'Total Tele', False),
    ('https://telecoms.com/feed/', 'Telecoms', False),
    ('https://telecomreseller.com/feed/', 'Telecom Reseller', False),
    ('https://www.telcomagazine.com/feed/', 'Telco Magazine', False),
    ('https://www.broadbandworldnews.com/rss.xml', 'Broadband World News', False),
    ('https://insidetowers.com/feed/', 'Inside Towers', False),
    ('https://www.wirelessweek.com/rss.xml', 'Wireless Week', False),
    ('https://www.telegeography.com/feed/', 'TeleGeography', False),
    ('https://www.vanillaplus.com/feed/', 'Vanilla Plus', False),
    ('https://developingtelecoms.com/feed', 'Developing Telecoms', False),
    ('https://www.mobileworldlive.com/feed/', 'Mobile World Live', False),
    ('https://www.commsupdate.com/feed/', 'Comms Update', False),
    ('https://www.sdxcentral.com/feed/', 'SDxCentral', False),
    ('https://www.networkworld.com/index.rss', 'Network World', False),
    ('https://tiaonline.org/feed/', 'TIA Online', False),
    ('https://www.tvtechnology.com/rss.xml', 'TV Technology', False),
    ('https://www.nexttv.com/rss.xml', 'NextTV', False),
    ('https://www.radioworld.com/feed/', 'Radio World', False),
    ('https://tvnewscheck.com/feed/', 'TVNewsCheck', False),
    ('https://www.rbr.com/feed/', 'RBR', False),
    ('https://www.insideradio.com/rss.xml', 'Inside Radio', False),
    ('https://www.allaccess.com/merge/archive/rss.xml', 'All Access', False),
    ('https://talkers.com/feed/', 'Talkers', False),
    ('https://radioink.com/feed/', 'Radio Ink', False),
    ('https://thedesk.net/feed/', 'The Desk', False),
    ('https://cordcuttersnews.com/feed/', 'Cord Cutters News', False),
    ('https://fccdata.org/feed/', 'FCC Data', False),
    ('https://www.benton.org/rss.xml', 'Benton Institute', False),
    ('https://publicknowledge.org/feed/', 'Public Knowledge', False),
    ('https://techfreedom.org/feed/', 'TechFreedom', False),
    ('https://www.eff.org/rss/updates.xml', 'EFF', False),
    ('https://www.law360.com/rss/articles', 'Law360', False),
    ('https://federalnewsnetwork.com/feed/', 'Federal News Network', False),
    ('https://www.govtech.com/rss', 'GovTech', False),
    ('https://www.natlawreview.com/recent/feed', 'National Law Review', False),
    ('https://www.scotusblog.com/feed/', 'SCOTUSblog', False),
    ('https://www.yalejreg.com/feed/', 'Yale JREG', False),
    ('https://www.brookings.edu/topic/technology-innovation/feed/', 'Brookings TechTank', False),
    ('https://itif.org/feed/', 'ITIF', False),
    ('https://www.aei.org/feed/', 'AEI', False),
    ('https://www.csis.org/rss.xml', 'CSIS', False),
    ('https://www.politico.com/rss/technology.xml', 'Politico', False),
    ('https://www.nextgov.com/rss/all/', 'Nextgov', False),
    ('https://www.bloomberglaw.com/feed', 'Bloomberg Law', False),
    ('https://feeds.arstechnica.com/arstechnica/index', 'Ars Technica', False),
    ('https://www.theverge.com/rss/index.xml', 'The Verge', False),
    ('https://techcrunch.com/feed/', 'TechCrunch', False),
    ('https://www.techdirt.com/feed/', 'TechDirt', False),
    ('https://www.wired.com/feed/rss', 'Wired', False),
    ('https://www.engadget.com/rss.xml', 'Engadget', False),
    ('https://gizmodo.com/feed/', 'Gizmodo', False),
    ('https://www.cnet.com/rss/news/', 'CNET', False),
    ('https://www.zdnet.com/news/rss.xml', 'ZDNet', False),
    ('https://venturebeat.com/feed/', 'VentureBeat', False),
    ('https://www.digitaltrends.com/feed/', 'Digital Trends', False),
    ('https://www.techradar.com/feeds/', 'TechRadar', False),
    ('https://www.pcmag.com/feeds/latest', 'PCMag', False),
    ('https://rss.slashdot.org/Slashdot/slashdotMain', 'Slashdot', False),
    ('https://mashable.com/feeds/rss/all', 'Mashable', False),
    ('https://www.tomsguide.com/feeds/all', "Tom's Guide", False),
    ('https://www.eweek.com/rss.xml', 'eWeek', False),
    ('https://www.crn.com/rss', 'CRN', False),
    ('https://www.cio.com/feed/', 'CIO', False),
    ('https://feeds.reuters.com/reuters/technologyNews', 'Reuters Technology', False),
    ('https://feeds.reuters.com/reuters/businessNews', 'Reuters Business', False),
    ('https://rsshub.app/apnews/topics/technology', 'AP News Technology', False),
    ('https://rsshub.app/apnews/topics/politics', 'AP News Politics', False),
    ('https://feeds.bloomberg.com/technology/news.rss', 'Bloomberg Technology', False),
    ('https://feeds.bloomberg.com/politics/news.rss', 'Bloomberg Politics', False),
    ('https://feeds.content.dowjones.io/public/rss/mw_technology', 'Wall Street Journal Tech', False),
    ('https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml', 'New York Times Tech', False),
    ('https://rss.nytimes.com/services/xml/rss/nyt/Politics.xml', 'New York Times Politics', False),
    ('https://feeds.washingtonpost.com/rss/business/technology', 'Washington Post Tech', False),
    ('https://thehill.com/feed/', 'The Hill', False),
    ('https://api.axios.com/feed/', 'Axios', False),
    ('https://rss.cnn.com/rss/cnn_tech.rss', 'CNN Tech', False),
    ('https://www.cbsnews.com/latest/rss/tech', 'CBS News Tech', False),
    ('https://feeds.nbcnews.com/nbcnews/public/tech', 'NBC News Tech', False),
    ('https://abcnews.go.com/abcnews/technologyheadlines', 'ABC News Tech', False),
    ('https://moxie.foxbusiness.com/google-publisher/technology.xml', 'Fox Business', False),
    ('https://rssfeeds.usatoday.com/UsatodaycomTech-TopStories', 'USA Today Tech', False),
    ('https://feeds.npr.org/1019/rss.xml', 'NPR Technology', False),
    ('https://feeds.npr.org/1006/rss.xml', 'NPR Business', False),
    ('https://www.forbes.com/innovation/feed/', 'Forbes Tech', False),
    ('https://fortune.com/feed/', 'Fortune', False),
    ('https://feeds.content.dowjones.io/public/rss/mw_topstories', 'MarketWatch', False),
    ('https://www.cnbc.com/id/19854910/device/rss/rss.html', 'CNBC Tech', False),
    ('https://www.cnbc.com/id/10000108/device/rss/rss.html', 'CNBC Telecom', False),
    ('https://www.darkreading.com/rss.xml', 'Dark Reading', False),
    ('https://www.securityweek.com/feed/', 'Security Week', False),
    ('https://www.cybersecuritydive.com/feeds/news/', 'Cybersecurity Dive', False),
    ('https://www.scmagazine.com/feed/', 'SC Magazine', False),
    ('https://www.cyberdefensemagazine.com/feed/', 'Cyber Defense Magazine', False),
    ('https://www.nexttv.com/rss/multichannel', 'Multichannel News', False),
    ('https://www.nexttv.com/rss/broadcasting-cable', 'Broadcasting & Cable', False),
    ('https://communicationsdaily.com/feed/', 'Communications Daily', False),
    ('https://spectrum.ieee.org/feeds/feed.rss', 'IEEE Spectrum', False),
    ('https://www.technologyreview.com/feed/', 'MIT Tech Review', False),
    ('https://www.opednews.com/populum/rss_telecom.php', 'Oped News Telecom', False),
    ('https://techpolicy.press/feed/', 'Tech Policy Press', False),
    ('https://www.protocol.com/feeds/feed.rss', 'Protocol', False),
    ('https://morningconsult.com/feed/', 'Morning Consult Tech', False),
    ('https://www.pewresearch.org/feed/', 'Pew Research Tech', False),
    ('https://www.govexec.com/rss/all/', 'Government Executive', False),
    ('https://fcw.com/rss/rss.ashx', 'Federal Computer Week', False),
    ('https://www.defenseone.com/rss/technology/', 'Defense One Tech', False),
    ('https://insidecybersecurity.com/rss.xml', 'Inside Cybersecurity', False),
    ('https://www.accessintel.com/feed/', 'Access Intelligence', False),
    ('https://www.telecomramblings.com/feed/', 'Telecom Ramblings', False),
    ('https://www.circleid.com/rss/posts/', 'CircleID', False),
    ('https://www.ip-watch.org/feed/', 'IP Watch', False),
    ('https://multichannelmerchant.com/feed/', 'Multichannel Merchant', False),
    ('https://www.satellitetoday.com/feed/', 'Satellite Today', False),
    ('https://www.satellitetoday.com/via-satellite/feed/', 'Via Satellite', False),
    ('https://spacenews.com/feed/', 'Space News', False),
    ('https://www.bbcmag.com/rss/', 'Broadband Communities', False),
    ('https://www.ispreview.co.uk/index.php/feed', 'ISP Review UK', False),
    ('https://www.telecomasia.net/rss.xml', 'Telecom Asia', False),
    ('https://www.telecomlead.com/feed', 'Telecom Lead', False),
    ('https://www.enterprisenetworkingplanet.com/feed/', 'Enterprise Networking Planet', False),
    ('https://www.datacenterknowledge.com/rss.xml', 'Data Center Knowledge', False),
    ('https://www.fiercehealthcare.com/rss/xml', 'Fierce Healthcare IT', False),
    ('https://www.fierceeducation.com/rss/xml', 'Fierce Education', False),
    ('https://www.ecommercetimes.com/rss-feed/', 'E-Commerce Times', False),
    ('https://linuxinsider.com/rss-feed/', 'LinuxInsider', False),
    ('https://www.technewsworld.com/rss-feed/', 'TechNewsWorld', False),
    ('https://www.macnewsworld.com/rss-feed/', 'MacNewsWorld', False),
    ('https://www.techrepublic.com/rssfeeds/articles/', 'Tech Republic', False),
    ('https://www.informationweek.com/rss_simple.asp', 'InformationWeek', False),
    ('https://www.computerworld.com/index.rss', 'Computerworld', False),
    ('https://www.infoworld.com/index.rss', 'InfoWorld', False),
    ('https://www.csoonline.com/index.rss', 'CSO Online', False),
    ('https://www.itworldcanada.com/blog/feed', 'IT World Canada', False),
    ('https://www.zdnet.com/topic/networking/rss.xml', 'ZD Net UK', False),
    ('https://www.theregister.com/headlines.atom', 'The Register', False),
    ('https://arstechnica.co.uk/feed/', 'Ars UK', False),
    ('https://hothardware.com/rss/news.aspx', 'Hot Hardware', False),
    ('https://www.extremetech.com/feed', 'Extreme Tech', False),
    ('https://www.hackread.com/feed/', 'Hack Read', False),
    ('https://www.bleepingcomputer.com/feed/', 'Bleeping Computer', False),
    ('https://krebsonsecurity.com/feed/', 'Krebs on Security', False),
    ('https://threatpost.com/feed/', 'Threatpost', False),
    ('https://therecord.media/feed', 'The Record', False),
    ('https://thecyberwire.com/feeds/rss.xml', 'CyberWire', False),
    ('https://www.lawfaremedia.org/feed', 'Lawfare', False),
    ('https://www.justsecurity.org/feed/', 'Just Security', False),
    ('https://abovethelaw.com/feed/', 'Above the Law', False),
    ('https://www.jdsupra.com/topics/telecommunications/rss/', 'JD Supra Telecom', False),
    ('https://www.jdsupra.com/topics/fcc/rss/', 'JD Supra FCC', False),
    ('https://www.lexology.com/rss/latest?topic=telecom', 'Lexology Telecom', False),
    ('https://www.mondaq.com/rss/telecommunications/', 'Mondaq Telecom', False),
    ('https://www.insideprivacy.com/feed/', 'Inside Privacy', False),
    ('https://iapp.org/news/rss/', 'IAPP News', False),
    ('https://fpf.org/feed/', 'Future of Privacy Forum', False),
    ('https://cdt.org/feed/', 'CDT', False),
    ('https://freepress.net/rss.xml', 'Free Press', False),
    ('https://www.media-alliance.org/feed/', 'Media Alliance', False),
    ('https://www.commoncause.org/feed/', 'Common Cause', False),
    ('https://www.consumerreports.org/cro/news/index.htm', 'Consumer Reports Tech', False),
    ('https://www.ftc.gov/feeds/press-release-rss.xml', 'FTC News', False),
    ('https://www.justice.gov/feeds/opa/justice-news.xml', 'DOJ Press', False),
    ('https://www.ftc.gov/feeds/business-guidance.xml', 'FTC Business', False),
    ('https://www.ntia.gov/rss.xml', 'NTIA', False),
    ('https://www.usac.org/rss/', 'USAC', False),
    ('https://www.rd.usda.gov/rss/updates', 'RUS USDA', False),
    ('https://fccwatch.com/feed/', 'FCC Watch', False),
    ('https://communicationslawyer.net/feed/', 'Communications Lawyer', False),
    ('https://telepolicyblog.wordpress.com/feed/', 'Telecom Policy', False),
    ('https://techliberation.com/feed/', 'Technology Liberation Front', False),
    ('https://truthonthemarket.com/feed/', 'Truth on the Market', False),
    ('https://www.competitionpolicyinternational.com/feed/', 'Competition Policy Intl', False),
    ('https://reason.com/tag/technology/feed/', 'Reason Tech', False),
    ('https://prospect.org/feeds/rss/', 'The American Prospect', False),
    ('https://www.theatlantic.com/feed/channel/technology/', 'The Atlantic Tech', False),
    ('https://www.thenation.com/subject/tech/feed/', 'The Nation', False),
    ('https://www.salon.com/topic/tech/feed', 'Salon Tech', False),
    ('https://slate.com/technology.rss', 'Slate Tech', False),
    ('https://www.vox.com/rss/technology/index.xml', 'Vox Tech', False),
    ('https://medium.com/feed/topic/technology', 'Medium Tech Policy', False),
    ('https://broadbandbreakfast.substack.com/feed', 'Substack Broadband', False),
    ('https://www.jdsupra.com/topics/broadband/rss/', 'JD Supra - Broadband', False),
    ('https://www.jdsupra.com/topics/net-neutrality/rss/', 'JD Supra - Net Neutrality', False),
    ('https://www.jdsupra.com/topics/media-law/rss/', 'JD Supra - Media Law', False),
    ('https://cei.org/feed/', 'Competitive Enterprise Inst', False),
    ('https://www.heritage.org/technology/rss', 'Heritage Foundation Tech', False),
    ('https://www.mercatus.org/rss/technology', 'Mercatus Center Tech', False),
    ('https://bipartisanpolicy.org/feed/', 'Bipartisan Policy Center', False),
    ('https://www.rstreet.org/feed/', 'R Street Institute', False),
    ('https://www.gao.gov/rss/reports.xml', 'Government Accountability Office', False),
    ('https://www.commerce.senate.gov/rss/feeds/?type=news', 'Senate Commerce Committee', False),
    ('https://energycommerce.house.gov/rss.xml', 'House Energy Commerce Comm', False),
    ('https://www.everycrsreport.com/feeds/all.rss', 'Congressional Research Service', False),
    ('https://www.tomshardware.com/feeds/all', "Tom's Hardware", False),
    ('https://www.anandtech.com/rss/', 'Anandtech', False),
    ('https://www.nextgov.com/rss/technology/', 'Nextgov - IT', False),
    ('https://statescoop.com/feed/', 'StateScoop', False),
    ('https://edscoop.com/feed/', 'EdScoop', False),
    ('https://cyberscoop.com/feed/', 'CyberScoop', False),
    ('https://fedscoop.com/feed/', 'FedScoop', False),
    ('https://www.meritalk.com/feed/', 'MeriTalk', False),
    ('https://www.govloop.com/feed/', 'GovLoop', False),
    ('https://www.techtarget.com/rss/SearchNetworking-News.xml', 'TechTarget Networking', False),
    ('https://www.techtarget.com/rss/SearchTelecom-News.xml', 'TechTarget Telecom', False),
    ('https://www.techtarget.com/rss/SearchSecurity-News.xml', 'TechTarget Security', False),
    ('https://www.techtarget.com/rss/SearchEnterpriseAI-News.xml', 'SearchEnterpriseAI', False),
    ('https://current.org/feed/', 'Current - Public Media', False),
    ('https://www.radioinfo.com.au/rss.xml', 'RadioInfo', False),
    ('https://rainnews.com/feed/', 'RAIN News - Audio/Radio', False),
    ('https://jacobin.com/feed/', 'Jacobin - Media', False),
    ('https://www.cjr.org/feed', 'Columbia Journalism Review', False),
    ('https://www.niemanlab.org/feed/', 'Nieman Lab', False),
    ('https://www.poynter.org/feed/', 'Poynter', False),
    ('https://www.mediapost.com/rss/', 'MediaPost', False),
    ('https://www.prnewswire.com/rss/news-releases-list.rss?tagABCSIC=5700000000', 'PR Newswire - Telecom', False),
    ('https://feed.businesswire.com/rss/home/?rss=G1&category=Telecommunications', 'Business Wire - Telecom', False),
    ('https://www.globenewswire.com/RssFeed/industry/9621-Telecommunications', 'Globe Newswire - Telecom', False),
    ('https://www.5gamericas.org/feed/', '5G Americas', False),
    ('https://www.5gtechnologyworld.com/feed/', '5G Technology World', False),
    ('https://www.rcrwireless.com/category/5g/feed', 'RCR Wireless 5G', False),
    ('https://www.fiercewireless.com/rss/5g-xml', 'FierceWireless 5G', False),
    ('https://www.lightreading.com/5g/rss.xml', 'Light Reading 5G', False),
    ('https://www.bell-labs.com/institute/feed/', 'Nokia Bell Labs Blog', False),
    ('https://www.ericsson.com/en/blog/rss', 'Ericsson Blog', False),
    ('https://www.qualcomm.com/news/blog/rss', 'Qualcomm Blog', False),
    ('https://www.t-mobile.com/news/rss.xml', 'T-Mobile Newsroom', False),
    ('https://www.verizon.com/about/news/rss', 'Verizon News', False),
    ('https://about.att.com/innovation/rss', 'AT&T Newsroom', False),
    ('https://corporate.comcast.com/news-information/news-feed/rss', 'Comcast Newsroom', False),
    ('https://corporate.charter.com/newsroom/rss', 'Charter Communications', False),
    ('https://www.ctia.org/rss/', 'CTIA Wireless', False),
    ('https://www.ustelecom.org/feed/', 'USTelecom', False),
    ('https://www.ncta.com/rss.xml', 'NCTA Cable', False),
    ('https://www.incompas.org/feed/', 'INCOMPAS', False),
    ('https://acaconnects.org/feed/', 'ACA Connects', False),
    ('https://www.wtaonline.org/feed/', 'WTA Telecom', False),
    ('https://www.ntca.org/feed/', 'NTCA Rural Broadband', False),
    ('https://www.wispa.org/feed/', 'WISPA Wireless ISP', False),
    ('https://www.natehome.com/feed/', 'NATE Tower Association', False),
    ('https://feeds.reuters.com/reuters/mediaNews', 'Reuters - Media', False),
    ('https://rsshub.app/apnews/topics/science', 'AP - Science Tech', False),
    ('https://feeds.bloomberg.com/industries/TelecommunicationsServices.rss', 'Bloomberg - Telecom', False),
    ('https://feeds.content.dowjones.io/public/rss/mw_media', 'Wall Street Journal - Media', False),
    ('https://www.ft.com/technology?format=rss', 'Financial Times - Tech', False),
    ('https://www.theguardian.com/technology/rss', 'The Guardian - Tech', False),
    ('https://feeds.bbci.co.uk/news/technology/rss.xml', 'BBC - Tech', False),
    ('https://www.politico.com/rss/media.xml', 'Politico - Media', False),
    ('https://www.politico.com/rss/congress.xml', 'Politico - Congress', False),
    ('https://www.wired.com/feed/category/business/latest/rss', 'Wired Business', False),
    ('https://feeds.arstechnica.com/arstechnica/tech-policy', 'Ars Technica - Policy', False),
    ('https://feeds.arstechnica.com/arstechnica/telecom', 'Ars Technica - Telecom', False),
    ('https://www.theverge.com/rss/policy/index.xml', 'The Verge - Policy', False),
    ('https://techcrunch.com/tag/government/feed/', 'TechCrunch - Government', False),
    ('https://api.axios.com/feed/axios/media-trends', 'Axios - Media Trends', False),
    ('https://api.axios.com/feed/axios/technology', 'Axios - Technology', False),
    ('https://api.axios.com/feed/axios/login', 'Axios - Login', False),
    ('https://www.pewresearch.org/internet/feed/', 'Pew Research - Tech', False),
    ('https://cyber.harvard.edu/feeds/news', 'Harvard Berkman Center', False),
    ('https://stacks.stanford.edu/feed', 'Stanford Internet Observatory', False),
    ('https://www.law.georgetown.edu/news/feed/', 'Georgetown Law Tech', False),
    ('https://law.duke.edu/news/rss/', 'Duke Law Tech', False),
    ('https://law.yale.edu/rss/news', 'Yale Law - Tech', False),
    ('https://www.law.gwu.edu/news/rss', 'George Washington Law', False),
    ('https://www.wcl.american.edu/impact/rss/', 'American University Law', False),
    ('https://www.chicagotribune.com/feed/', 'Chicago Tribune', False),
    ('https://www.latimes.com/local/rss2.0.xml', 'Los Angeles Times', False),
    ('https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml', 'New York Times (Home)', False),
    ('https://www.inquirer.com/arcio/rss/', 'Philadelphia Inquirer', False),
    ('https://www.sfgate.com/default/feed/SFGate-Latest-News-2960713.php', 'SF Gate', False),
    ('https://rssfeeds.usatoday.com/usatoday-NewsTopStories', 'USA Today (Top Stories)', False),
    ('https://feeds.washingtonpost.com/rss/national', 'Washington Post (National)', False),
    ('https://www.ajc.com/news/rss.xml', 'Atlanta Journal-Constitution', False),
    ('https://www.statesman.com/arc/outboundfeeds/rss/', 'Austin American-Statesman', False),
    ('https://www.baltimoresun.com/arcio/rss/', 'Baltimore Sun', False),
    ('https://www.bostonglobe.com/rss/homepage', 'Boston Globe', False),
    ('https://www.bostonherald.com/feed/', 'Boston Herald', False),
    ('https://chicago.suntimes.com/rss/index.xml', 'Chicago Sun-Times', False),
    ('https://www.cleveland.com/arc/outboundfeeds/rss/', 'Cleveland Plain Dealer', False),
    ('https://www.dallasnews.com/arc/outboundfeeds/rss/', 'Dallas Morning News', False),
    ('https://www.freep.com/arcio/rss/', 'Detroit Free Press', False),
    ('https://www.houstonchronicle.com/arc/outboundfeeds/rss/', 'Houston Chronicle', False),
    ('https://www.kansascity.com/arc/outboundfeeds/rss/', 'Kansas City Star', False),
    ('https://www.miamiherald.com/arc/outboundfeeds/rss/', 'Miami Herald', False),
    ('https://www.startribune.com/local/rss', 'Minneapolis Star Tribune', False),
    ('https://www.nydailynews.com/arc/outboundfeeds/rss/', 'NY Daily News', False),
    ('https://nypost.com/feed/', 'New York Post', False),
    ('https://www.nj.com/arc/outboundfeeds/rss/', 'NJ.com', False),
    ('https://www.oregonlive.com/arc/outboundfeeds/rss/', 'Oregonian', False),
    ('https://www.post-gazette.com/rss/homepage', 'Pittsburgh Post-Gazette', False),
    ('https://www.mercurynews.com/arc/outboundfeeds/rss/', 'San Jose Mercury News', False),
    ('https://www.seattletimes.com/feed/', 'Seattle Times', False),
    ('https://www.tampabay.com/feed/', 'Tampa Bay Times', False),
    ('https://www.azcentral.com/arc/outboundfeeds/rss/', 'Arizona Republic', False),
    ('https://www.washingtontimes.com/rss/headlines/news/', 'Washington Times', False),
    ('https://feeds.apnews.com/rss/topnews', 'AP News (Top)', False),
    ('https://adage.com/rss/technology', 'Ad Age', False),
    ('https://feeds.thedailybeast.com/rss/articles', 'Daily Beast', False),
    ('https://www.economist.com/technology/rss.xml', 'Economist Tech', False),
    ('https://www.fiercecable.com/rss/xml', 'Fierce Cable', False),
    ('https://www.fiercetelecom.com/rss/xml', 'Fierce Telecom', False),
    ('https://www.hollywoodreporter.com/feed/', 'Hollywood Reporter', False),
    ('https://rollcall.com/feed/', 'Roll Call', False),
    ('https://variety.com/feed/', 'Variety', False),
    ('https://www.thewrap.com/feed/', 'The Wrap', False),
    ('https://www.fastcompany.com/latest/rss?x=1', 'Fast Company', False),
    ('https://www.huffpost.com/section/front-page/feed', 'HuffPost', False),
    ('https://www.vice.com/en/section/tech/rss', 'Vice Motherboard', False),
    ('https://www.telecompetitor.com/feed/', 'Telecompetitor', False),
    ('https://awfulannouncing.com/feed/', 'Awful Announcing', False),
    ('https://www.democracynow.org/democracynow.rss', 'Democracy Now', False),
    ('https://feeds.npr.org/1001/rss.xml', 'NPR Homepage', False),
    ('https://www.nationaljournal.com/rss', 'National Journal', False),
    ('https://www.dslreports.com/rss', 'DSLReports', False),
]
