#!/bin/bash
set -euo pipefail

echo "=== Configuring App Service health check ==="
echo "This tells Azure to monitor /health and auto-restart unhealthy instances"
echo ""
echo "BEFORE RUNNING: confirm the azurewebsites.net hostname is in ALLOWED_HOSTS."
echo "TrustedHostMiddleware returns 400 on EVERY path including /health for an"
echo "unlisted host. Enabling the probe first would fail every check and pull"
echo "every instance out of rotation."
echo ""
echo "  az webapp config appsettings list --name Docuaction --resource-group rg-docuaction-prod \\"
echo "    --query \"[?name=='ALLOWED_HOSTS'].value\" -o tsv"
echo ""
echo "Production:"
echo "  az webapp config set --name Docuaction --resource-group rg-docuaction-prod \\"
echo "    --generic-configurations '{\"healthCheckPath\": \"/health\"}'"
echo ""
echo "Dev:"
echo "  az webapp config set --name docuaction-dev --resource-group rg-docuaction-dev \\"
echo "    --generic-configurations '{\"healthCheckPath\": \"/health\"}'"
echo ""
echo "Verify:"
echo "  az webapp config show --name Docuaction --resource-group rg-docuaction-prod \\"
echo "    --query healthCheckPath -o tsv"
echo ""
echo "Or in the portal: App Service -> Health check -> /health configured"
echo ""
echo "NOTE: instance replacement requires more than one worker. On a single-instance"
echo "plan this buys a monitoring signal, not self-healing. Check with:"
echo "  az appservice plan list -g rg-docuaction-prod --query [].numberOfWorkers -o tsv"
echo ""
echo "NOTE: /health probes external TEFCA connectors behind a cache. It returns 200"
echo "with status degraded when they are down, which is the correct behaviour -"
echo "a third-party outage must not cause Azure to recycle healthy instances."
