#!/bin/bash
set -euo pipefail

echo "=== Disabling FTP on both App Services ==="
echo ""
echo "Why: FTP is a second write path into wwwroot that bypasses the deployment"
echo "pipeline entirely - no artifact verification, no .env check, no deployment"
echo "record. Nothing in this project deploys over FTP; production uses a"
echo "pre-built pydeps zip and dev uses the same command with an Oryx build."
echo ""
echo "Current state:"
echo "  az webapp config show --name Docuaction --resource-group rg-docuaction-prod --query ftpsState -o tsv"
echo "  az webapp config show --name docuaction-dev --resource-group rg-docuaction-dev --query ftpsState -o tsv"
echo ""
echo "Production:"
echo "  az webapp config set --name Docuaction --resource-group rg-docuaction-prod --ftps-state Disabled"
echo ""
echo "Dev:"
echo "  az webapp config set --name docuaction-dev --resource-group rg-docuaction-dev --ftps-state Disabled"
echo ""
echo "Verify:"
echo "  az webapp config show --name Docuaction --resource-group rg-docuaction-prod --query ftpsState"
echo ""
echo "Impact: none on zip deploy or on the Kudu/SCM endpoint, which is a separate"
echo "channel and is what CI uses. Disabled turns off both FTP and FTPS. Use"
echo "FtpsOnly only if a specific tool needs it - identify that tool first,"
echo "because the answer is usually nothing."
