#!/usr/bin/env python3
"""
Reset the QA test-account passwords to fresh, unique, random credentials.

Run by an administrator with their OWN admin bearer token. Generates one distinct
16-character password per account, applies it through the authenticated admin API
(POST /api/admin/users/{id}/set-password), verifies each account can log in, and
writes the credentials to a single gitignored file.

Passwords are NEVER printed to stdout — terminal scrollback and CI logs are not a
place for credentials. They exist only in the output file (mode 0600 where the OS
supports it).

Usage
  export DOCUACTION_ADMIN_TOKEN='<your admin access_token>'
  python scripts/reset_qa_passwords.py --dry-run          # show the plan, change nothing
  python scripts/reset_qa_passwords.py                    # execute

Notes on the endpoints this drives (backend/app/api/admin_users.py):
  - set-password requires an admin; resetting an account that is itself an admin
    additionally requires a SUPER admin (email in core.security.ADMIN_EMAILS).
  - Every reset sets users.tokens_revoked_at, terminating that account's existing
    sessions. admin@docuaction.io is therefore reset LAST: if you authenticated as
    that account, its reset invalidates the very token this script is using.
"""
import argparse
import json
import os
import secrets
import string
import sys
import urllib.error
import urllib.parse
import urllib.request
from datetime import datetime, timezone

DEFAULT_BASE_URL = "https://docuaction-dev.azurewebsites.net"

# admin@ is reset LAST — see the module docstring (session termination).
ACCOUNTS = [
    "viewer@docuaction.io",
    "analyst@docuaction.io",
    "reviewer@docuaction.io",
    "testadmin@docuaction.io",
    "qalead@docuaction.io",
    "admin@docuaction.io",
]

OUTPUT_FILE = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "docs", "QA_CREDENTIALS.md"
)

PASSWORD_LENGTH = 16
# Special characters are restricted to a subset of the set accepted by
# password_reset._validate_password that is safe to paste into a shell, a URL, or a
# JSON body: no quotes, backslashes, or redirect characters.
SPECIALS = "!@#$%^&*?.,"
POOL = string.ascii_letters + string.digits + SPECIALS


def gen_password(n: int = PASSWORD_LENGTH) -> str:
    """Random password guaranteed to satisfy the platform's complexity rules
    (upper + lower + digit + special), via rejection sampling so the distribution
    stays uniform over the qualifying strings."""
    while True:
        pw = "".join(secrets.choice(POOL) for _ in range(n))
        if (any(c.isupper() for c in pw) and any(c.islower() for c in pw)
                and any(c.isdigit() for c in pw) and any(c in SPECIALS for c in pw)):
            return pw


def api(method: str, url: str, token: str = None, payload: dict = None, timeout: int = 30):
    """Minimal JSON HTTP client (stdlib only — no dependency install needed).
    Returns (status_code, parsed_body_or_text)."""
    data = json.dumps(payload).encode() if payload is not None else None
    req = urllib.request.Request(url, data=data, method=method)
    req.add_header("Content-Type", "application/json")
    req.add_header("Accept", "application/json")
    if token:
        req.add_header("Authorization", "Bearer %s" % token)
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            raw = resp.read()
            try:
                return resp.status, json.loads(raw) if raw else None
            except ValueError:
                return resp.status, raw.decode("utf-8", "replace")
    except urllib.error.HTTPError as e:
        raw = e.read().decode("utf-8", "replace")
        try:
            return e.code, json.loads(raw)
        except ValueError:
            return e.code, raw
    except urllib.error.URLError as e:
        return 0, "connection error: %s" % e.reason


def detail(body) -> str:
    if isinstance(body, dict):
        return str(body.get("detail") or body)
    return str(body)


def write_credentials_file(path: str, base_url: str, rows: list, shared: bool = False) -> None:
    """Write the credential file with restrictive permissions, creating it via
    os.open so it is never briefly world-readable."""
    os.makedirs(os.path.dirname(path), exist_ok=True)
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ")
    lines = [
        "# QA Test Account Credentials",
        "",
        "> **DO NOT COMMIT.** This file is gitignored and contains live credentials.",
        "> Delete it once the QA team has stored the passwords in their own vault.",
        "",
        "| Field | Value |",
        "|---|---|",
        "| Environment | `%s` |" % base_url,
        "| Generated (UTC) | %s |" % stamp,
        "| Generated by | `scripts/reset_qa_passwords.py` |",
        "| Password scheme | %s |" % ("**one shared password across all accounts**"
                                      if shared else "unique per account"),
        "",
        "Resetting a password terminates that account's existing sessions, so any",
        "previously issued token is now invalid.",
        "",]
    if shared:
        lines += [
            "> **Shared-credential mode.** Every account below, including the super-admin",
            "> identity `admin@docuaction.io`, uses the same password. Anyone holding it can",
            "> authenticate at any role, which means the role separation this environment's",
            "> RBAC evidence relies on is not enforced by authentication while this is in",
            "> effect. Accepted by the owner for the dev environment.",
            "",
        ]
    lines += [
        "| Account | Password | Reset | Login verified |",
        "|---|---|---|---|",
    ]
    for r in rows:
        lines.append("| `%s` | `%s` | %s | %s |" % (
            r["email"], r.get("password") or "—", r["reset"], r["verified"]))
    lines += [
        "",
        "## Distribution",
        "",
        "Share each password with the person who needs it — not the whole file to the",
        "whole team. `admin@docuaction.io` is a super-admin identity (24-hour tokens,",
        "unrestricted access, hardcoded in `app/core/security.py`); it should go to",
        "fewer people than the role accounts, if it needs to go out at all.",
        "",
        "## Rotation",
        "",
        "Re-run the script to rotate. It overwrites this file with new passwords.",
        "",
    ]
    fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    try:
        os.chmod(path, 0o600)  # best-effort; Windows ACLs do not map cleanly
    except OSError:
        pass


def main() -> int:
    p = argparse.ArgumentParser(description="Reset QA test-account passwords to unique random values.")
    p.add_argument("--base-url", default=os.environ.get("DOCUACTION_BASE_URL", DEFAULT_BASE_URL),
                   help="API base URL (default: %s)" % DEFAULT_BASE_URL)
    p.add_argument("--output", default=OUTPUT_FILE, help="Credential file path (default: docs/QA_CREDENTIALS.md)")
    p.add_argument("--dry-run", action="store_true", help="Show what would happen; change nothing.")
    p.add_argument("--yes", action="store_true", help="Skip the confirmation prompt.")
    p.add_argument("--allow-nondev", action="store_true",
                   help="Required to target a host whose name does not contain 'dev'.")
    p.add_argument("--no-verify", action="store_true", help="Skip the post-reset login check.")
    p.add_argument("--shared-password", metavar="VALUE", default=None,
                   help="Set EVERY account to this one password instead of generating unique ones. "
                        "Note: the value lands in your shell history and process list.")
    p.add_argument("--shared-password-env", metavar="VARNAME", default=None,
                   help="Same as --shared-password, but read the value from this environment "
                        "variable so it stays out of argv and shell history.")
    args = p.parse_args()

    shared = args.shared_password
    if args.shared_password_env:
        shared = os.environ.get(args.shared_password_env, "")
        if not shared:
            print("ERROR: %s is unset or empty." % args.shared_password_env, file=sys.stderr)
            return 2
    if shared is not None:
        # Fail before any account is touched rather than part-way through: set-password
        # requires >= 8 chars (admin_users.py:397) and the reset flow additionally
        # requires upper/lower/digit/special (password_reset._validate_password), so a
        # value failing the latter would work now but break the reset link flow later.
        problems = []
        if len(shared) < 8:
            problems.append("at least 8 characters")
        if not any(c.isupper() for c in shared):
            problems.append("an uppercase letter")
        if not any(c.islower() for c in shared):
            problems.append("a lowercase letter")
        if not any(c.isdigit() for c in shared):
            problems.append("a number")
        if not any(c in '!@#$%^&*(),.?":{}|<>' for c in shared):
            problems.append("a special character")
        if problems:
            print("ERROR: shared password needs %s." % ", ".join(problems), file=sys.stderr)
            return 2

    base_url = args.base_url.rstrip("/")
    host = urllib.parse.urlparse(base_url).hostname or ""

    # Guard rail: this script exists to reset SHARED TEST accounts. Pointing it at a
    # production host would reset real users' credentials and revoke their sessions.
    if "dev" not in host and not args.allow_nondev:
        print("REFUSING: host %r does not look like a dev environment." % host, file=sys.stderr)
        print("If this is intentional, re-run with --allow-nondev.", file=sys.stderr)
        return 2

    token = os.environ.get("DOCUACTION_ADMIN_TOKEN", "").strip()
    if not token and not args.dry_run:
        print("ERROR: set DOCUACTION_ADMIN_TOKEN to your admin access_token.", file=sys.stderr)
        print("  (Passed via the environment, not argv - argv is visible to other processes.)", file=sys.stderr)
        return 2

    print("Environment : %s" % base_url)
    print("Accounts    : %d" % len(ACCOUNTS))
    print("Output      : %s" % args.output)
    print("Passwords   : %s" % ("ONE SHARED PASSWORD for all accounts" if shared is not None
                                else "unique per account"))
    print("Mode        : %s" % ("DRY RUN - nothing will change" if args.dry_run else "EXECUTE"))
    if shared is not None:
        print()
        print("NOTE: a shared password means any QA member holding it can authenticate as")
        print("      admin@docuaction.io, a super-admin identity (app/core/security.py:22).")
        print("      Consider logging this in docs/RISK_ACCEPTANCE_REGISTER.md.")
    print()

    if args.dry_run:
        for email in ACCOUNTS:
            print("  would reset  %s" % email)
        print("\nDry run complete. No requests were sent, no file written.")
        return 0

    if not args.yes:
        print("This will reset the password of each account above and terminate their")
        print("existing sessions. The credential file will be OVERWRITTEN.")
        try:
            if input("Proceed? [y/N] ").strip().lower() not in ("y", "yes"):
                print("Aborted.")
                return 1
        except (EOFError, KeyboardInterrupt):
            print("\nAborted.")
            return 1
        print()

    # 1. Resolve emails -> user ids.
    status, body = api("GET", "%s/api/admin/users" % base_url, token=token)
    if status != 200:
        print("ERROR: GET /api/admin/users returned %s: %s" % (status, detail(body)), file=sys.stderr)
        if status == 401:
            print("  Token is invalid or expired. Log in again to get a fresh one.", file=sys.stderr)
        elif status == 403:
            print("  That token is not an admin.", file=sys.stderr)
        return 1

    by_email = {u["email"].lower(): u for u in body}
    missing = [e for e in ACCOUNTS if e.lower() not in by_email]
    if missing:
        print("WARNING: these accounts do not exist and will be skipped:")
        for e in missing:
            print("  - %s" % e)
        print("  (Create them via POST /api/admin/users/invite if QA needs them.)")
        print()

    # 2. Reset each account, then verify it can log in.
    rows = []
    failures = 0
    for email in ACCOUNTS:
        user = by_email.get(email.lower())
        if not user:
            rows.append({"email": email, "password": None, "reset": "SKIPPED — no such account",
                         "verified": "n/a"})
            continue

        password = shared if shared is not None else gen_password()
        status, body = api("POST", "%s/api/admin/users/%s/set-password" % (base_url, user["id"]),
                           token=token, payload={"new_password": password})
        if status != 200:
            failures += 1
            print("  FAIL   %-26s reset failed (%s: %s)" % (email, status, detail(body)))
            if status == 403:
                print("         Resetting an admin account requires a super-admin token.")
            rows.append({"email": email, "password": None,
                         "reset": "FAILED (%s)" % status, "verified": "n/a"})
            continue

        verified = "not checked"
        if not args.no_verify:
            vstatus, vbody = api("POST", "%s/api/auth/login" % base_url,
                                 payload={"email": email, "password": password})
            if vstatus == 200 and isinstance(vbody, dict) and vbody.get("access_token"):
                verified = "yes (200 + access_token)"
            else:
                failures += 1
                verified = "NO (%s: %s)" % (vstatus, detail(vbody))
            print("  ok     %-26s reset; login %s" % (email, verified))
        else:
            print("  ok     %-26s reset" % email)

        rows.append({"email": email, "password": password, "reset": "yes", "verified": verified})

    # 3. Write the credential file.
    write_credentials_file(args.output, base_url, rows, shared=shared is not None)
    print()
    print("Credentials written to %s (mode 0600)." % args.output)
    print("Passwords were not printed here by design — read them from that file.")

    if failures:
        print("\n%d step(s) failed. Check the table in the output file." % failures, file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
