#!/bin/bash
# Creates Azure Monitor alert rules for DocuAction production
# Run once to set up, then manage through Azure Portal

set -euo pipefail

RG="rg-docuaction-prod"
APP="Docuaction"
INSIGHTS="docuaction-appinsights"
ACTION_GROUP="docuaction-alerts"
EMAIL="imran@agtbi.com"
SUB="6ce81f40-7f0f-4e6d-97e3-2569b4d18611"
SCOPE="/subscriptions/$SUB/resourceGroups/$RG/providers/Microsoft.Web/sites/$APP"

echo "=== Creating action group ==="
echo "  az monitor action-group create \\"
echo "    --resource-group $RG \\"
echo "    --name $ACTION_GROUP \\"
echo "    --short-name DocuAlert \\"
echo "    --action email admin $EMAIL"
echo ""
echo "  Create the action group FIRST. An alert rule with no action group fires"
echo "  into nothing and still looks configured in the portal."
echo ""
echo "=== Alert: HTTP 5xx rate ==="
echo "  az monitor metrics alert create \\"
echo "    --resource-group $RG \\"
echo "    --name High-5xx-Rate \\"
echo "    --scopes $SCOPE \\"
echo "    --condition 'total Http5xx > 10' \\"
echo "    --window-size 5m \\"
echo "    --action $ACTION_GROUP"
echo ""
echo "=== Alert: Response time above 5s ==="
echo "  az monitor metrics alert create \\"
echo "    --resource-group $RG \\"
echo "    --name Slow-Response \\"
echo "    --scopes $SCOPE \\"
echo "    --condition 'avg HttpResponseTime > 5' \\"
echo "    --window-size 5m \\"
echo "    --action $ACTION_GROUP"
echo ""
echo "=== Alert: Health check failures ==="
echo "  az monitor metrics alert create \\"
echo "    --resource-group $RG \\"
echo "    --name Health-Check-Failed \\"
echo "    --scopes $SCOPE \\"
echo "    --condition 'total HealthCheckStatus < 1' \\"
echo "    --window-size 5m \\"
echo "    --action $ACTION_GROUP"
echo ""
echo "NOTE: the health check alert only produces a signal once healthCheckPath is"
echo "configured on the App Service. Run scripts/configure-health-check.sh first,"
echo "or this rule evaluates a metric that is never emitted."
echo ""
echo "NOTE: do NOT alert on the exit status of az webapp deploy. The CLI reports"
echo "connection failures while the deployment is still succeeding server-side,"
echo "so such an alert produces false alarms. Key deployment alerting on the"
echo "server-side deployment record instead:"
echo "  az webapp log deployment list -n $APP -g $RG --query [0].status -o tsv"
echo "  0=pending 1=building 3=failed 4=success"
echo ""
echo "App Insights component for availability web tests: $INSIGHTS"
